# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.update_document_and_send_request import UpdateDocumentAndSendRequest

class TestUpdateDocumentAndSendRequest(unittest.TestCase):
    """UpdateDocumentAndSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDocumentAndSendRequest:
        """Test UpdateDocumentAndSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDocumentAndSendRequest`
        """
        model = UpdateDocumentAndSendRequest()
        if include_optional:
            return UpdateDocumentAndSendRequest(
                test_mode = True,
                name = '',
                subject = '',
                message = '',
                expires_in = 1,
                reminders = True,
                apply_signing_order = True,
                api_application_id = '',
                embedded_signing = True,
                embedded_signing_notifications = True,
                custom_requester_name = '',
                custom_requester_email = '',
                redirect_url = '',
                allow_decline = True,
                allow_reassign = True,
                decline_redirect_url = '',
                metadata = {
                    'key' : ''
                    },
                labels = [
                    signwell_sdk.models.label_request.LabelRequest(
                        name = '', )
                    ],
                checkbox_groups = [
                    signwell_sdk.models.checkbox_groups_inner.CheckboxGroups_inner(
                        group_name = '', 
                        recipient_id = '', 
                        checkbox_ids = [
                            ''
                            ], 
                        validation = 'minimum', 
                        required = True, 
                        min_value = 56, 
                        max_value = 56, 
                        exact_value = 56, )
                    ]
            )
        else:
            return UpdateDocumentAndSendRequest(
        )
        """

    def testUpdateDocumentAndSendRequest(self):
        """Test UpdateDocumentAndSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
