# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.api_application_api import ApiApplicationApi


class TestApiApplicationApi(unittest.TestCase):
    """ApiApplicationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApplicationApi()

    def tearDown(self) -> None:
        pass

    def test_delete_api_application(self) -> None:
        """Test case for delete_api_application

        Delete API Application
        """
        pass

    def test_get_api_application(self) -> None:
        """Test case for get_api_application

        Get API Application
        """
        pass


if __name__ == '__main__':
    unittest.main()
