# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.bulk_send_validate_csv_response import BulkSendValidateCsvResponse

class TestBulkSendValidateCsvResponse(unittest.TestCase):
    """BulkSendValidateCsvResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSendValidateCsvResponse:
        """Test BulkSendValidateCsvResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSendValidateCsvResponse`
        """
        model = BulkSendValidateCsvResponse()
        if include_optional:
            return BulkSendValidateCsvResponse(
                bulk_send_csv = '',
                template_ids = [
                    ''
                    ],
                skip_row_errors = True,
                api_application_id = '',
                name = '',
                subject = '',
                message = '',
                apply_signing_order = True
            )
        else:
            return BulkSendValidateCsvResponse(
                bulk_send_csv = '',
                template_ids = [
                    ''
                    ],
        )
        """

    def testBulkSendValidateCsvResponse(self):
        """Test BulkSendValidateCsvResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
