# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.bulk_send_api import BulkSendApi


class TestBulkSendApi(unittest.TestCase):
    """BulkSendApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BulkSendApi()

    def tearDown(self) -> None:
        pass

    def test_create_bulk_send(self) -> None:
        """Test case for create_bulk_send

        Create Bulk Send
        """
        pass

    def test_get_bulk_send(self) -> None:
        """Test case for get_bulk_send

        Get Bulk Send
        """
        pass

    def test_get_bulk_send_csv_template(self) -> None:
        """Test case for get_bulk_send_csv_template

        Get Bulk Send CSV Template
        """
        pass

    def test_get_bulk_send_documents(self) -> None:
        """Test case for get_bulk_send_documents

        Get Bulk Send Documents
        """
        pass

    def test_list_bulk_sends(self) -> None:
        """Test case for list_bulk_sends

        List Bulk Sendings
        """
        pass

    def test_validate_bulk_send_csv(self) -> None:
        """Test case for validate_bulk_send_csv

        Validate Bulk Send CSV
        """
        pass


if __name__ == '__main__':
    unittest.main()
