# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.create_bulk_send_request import CreateBulkSendRequest

class TestCreateBulkSendRequest(unittest.TestCase):
    """CreateBulkSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBulkSendRequest:
        """Test CreateBulkSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBulkSendRequest`
        """
        model = CreateBulkSendRequest()
        if include_optional:
            return CreateBulkSendRequest(
                template_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
                bulk_send_csv = 'bmFtZSxlbWFpbApUZXN0LHRlc3RAZXhhbXBsZS5jb20K',
                skip_row_errors = True,
                api_application_id = '',
                name = '',
                subject = '',
                message = '',
                apply_signing_order = True,
                custom_requester_name = '',
                custom_requester_email = ''
            )
        else:
            return CreateBulkSendRequest(
                template_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
                bulk_send_csv = 'bmFtZSxlbWFpbApUZXN0LHRlc3RAZXhhbXBsZS5jb20K',
        )
        """

    def testCreateBulkSendRequest(self):
        """Test CreateBulkSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
