# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_template_response_copied_placeholders_inner import DocumentTemplateResponseCopiedPlaceholdersInner

class TestDocumentTemplateResponseCopiedPlaceholdersInner(unittest.TestCase):
    """DocumentTemplateResponseCopiedPlaceholdersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentTemplateResponseCopiedPlaceholdersInner:
        """Test DocumentTemplateResponseCopiedPlaceholdersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentTemplateResponseCopiedPlaceholdersInner`
        """
        model = DocumentTemplateResponseCopiedPlaceholdersInner()
        if include_optional:
            return DocumentTemplateResponseCopiedPlaceholdersInner(
                id = '',
                placeholder_id = '',
                name = '',
                subject = '',
                message = '',
                preassigned_recipient_name = '',
                preassigned_recipient_email = ''
            )
        else:
            return DocumentTemplateResponseCopiedPlaceholdersInner(
                name = '',
        )
        """

    def testDocumentTemplateResponseCopiedPlaceholdersInner(self):
        """Test DocumentTemplateResponseCopiedPlaceholdersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
