# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.me_api import MeApi


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeApi()

    def tearDown(self) -> None:
        pass

    def test_get_me(self) -> None:
        """Test case for get_me

        Get credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
