# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.text_validation import TextValidation

class TestTextValidation(unittest.TestCase):
    """TextValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextValidation(self):
        """Test TextValidation"""
        # inst = TextValidation()

if __name__ == '__main__':
    unittest.main()
