# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.me_response_user import MeResponseUser

class TestMeResponseUser(unittest.TestCase):
    """MeResponseUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeResponseUser:
        """Test MeResponseUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeResponseUser`
        """
        model = MeResponseUser()
        if include_optional:
            return MeResponseUser(
                id = '',
                name = '',
                email = '',
                has_google_registration = True,
                first_name = '',
                preferences = signwell_sdk.models.me_response_user_preferences.MeResponse_user_preferences(
                    sales_document = True, 
                    time_zone = '', 
                    smart_fields = True, )
            )
        else:
            return MeResponseUser(
                id = '',
                name = '',
                email = '',
        )
        """

    def testMeResponseUser(self):
        """Test MeResponseUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
