# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.bulk_send_create_response import BulkSendCreateResponse

class TestBulkSendCreateResponse(unittest.TestCase):
    """BulkSendCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSendCreateResponse:
        """Test BulkSendCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSendCreateResponse`
        """
        model = BulkSendCreateResponse()
        if include_optional:
            return BulkSendCreateResponse(
                id = '',
                template_ids = [
                    ''
                    ],
                api_application_id = '',
                documents_count = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_id = '',
                status = ''
            )
        else:
            return BulkSendCreateResponse(
                id = '',
                template_ids = [
                    ''
                    ],
                documents_count = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = '',
        )
        """

    def testBulkSendCreateResponse(self):
        """Test BulkSendCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
