# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.checkbox_groups_inner import CheckboxGroupsInner

class TestCheckboxGroupsInner(unittest.TestCase):
    """CheckboxGroupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckboxGroupsInner:
        """Test CheckboxGroupsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckboxGroupsInner`
        """
        model = CheckboxGroupsInner()
        if include_optional:
            return CheckboxGroupsInner(
                group_name = '',
                recipient_id = '',
                checkbox_ids = [
                    ''
                    ],
                validation = 'minimum',
                required = True,
                min_value = 56,
                max_value = 56,
                exact_value = 56
            )
        else:
            return CheckboxGroupsInner(
                group_name = '',
                recipient_id = '',
                checkbox_ids = [
                    ''
                    ],
        )
        """

    def testCheckboxGroupsInner(self):
        """Test CheckboxGroupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
