# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.update_recipients_map_inner import UpdateRecipientsMapInner

class TestUpdateRecipientsMapInner(unittest.TestCase):
    """UpdateRecipientsMapInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRecipientsMapInner:
        """Test UpdateRecipientsMapInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRecipientsMapInner`
        """
        model = UpdateRecipientsMapInner()
        if include_optional:
            return UpdateRecipientsMapInner(
                id = '',
                name = '',
                email = 'jane@example.com',
                subject = '',
                message = '',
                passcode = ''
            )
        else:
            return UpdateRecipientsMapInner(
                id = '',
                name = '',
                email = 'jane@example.com',
        )
        """

    def testUpdateRecipientsMapInner(self):
        """Test UpdateRecipientsMapInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
