# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_response import DocumentResponse

class TestDocumentResponse(unittest.TestCase):
    """DocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentResponse:
        """Test DocumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentResponse`
        """
        model = DocumentResponse()
        if include_optional:
            return DocumentResponse(
                test_mode = True,
                id = '',
                api_application_id = '',
                requester_email_address = '',
                custom_requester_name = '',
                custom_requester_email = '',
                name = '',
                subject = '',
                message = '',
                metadata = {
                    'key' : ''
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                recipients = [
                    signwell_sdk.models.document_response_recipients_inner.DocumentResponse_recipients_inner(
                        id = '', 
                        name = '', 
                        email = '', 
                        body = '', 
                        message = '', 
                        subject = '', 
                        send_email = True, 
                        send_email_delay = 56, 
                        signing_order = 56, 
                        signing_url = '', 
                        embedded_signing_url = '', 
                        bounced = True, 
                        bounced_details = '', 
                        attachment_requests = [
                            signwell_sdk.models.attachment_request_info.AttachmentRequestInfo(
                                name = '', 
                                url = '', 
                                required = True, )
                            ], 
                        passcode = '', 
                        status = '', )
                    ],
                status = '',
                reminders = True,
                archived = True,
                embedded_signing = True,
                embedded_edit_url = '',
                embedded_preview_url = '',
                apply_signing_order = True,
                redirect_url = '',
                decline_redirect_url = '',
                language = '',
                expires_in = 56,
                decline_message = '',
                error_message = '',
                template_id = '',
                template_ids = [
                    ''
                    ],
                embedded_signing_notifications = True,
                attachment_requests = [
                    signwell_sdk.models.document_response_attachment_requests_inner.DocumentResponse_attachment_requests_inner(
                        name = '', 
                        recipient_id = '', 
                        required = True, )
                    ],
                files = [
                    signwell_sdk.models.file_info.FileInfo(
                        name = '', 
                        pages_number = 56, )
                    ],
                copied_contacts = [
                    signwell_sdk.models.copied_contact_info.CopiedContactInfo(
                        id = '', 
                        name = '', 
                        email = '', )
                    ],
                fields = [
                    [
                        signwell_sdk.models.document_response_fields_inner_inner.DocumentResponse_fields_inner_inner(
                            x = 1.337, 
                            y = 1.337, 
                            page = 56, 
                            recipient = signwell_sdk.models.document_response_fields_inner_inner_recipient.DocumentResponse_fields_inner_inner_recipient(
                                email = '', 
                                name = '', ), 
                            api_id = '', 
                            name = '', 
                            date_format = 'MM/DD/YYYY', 
                            fixed_width = True, 
                            formula = '', 
                            label = '', 
                            lock_sign_date = True, 
                            required = True, 
                            type = 'initials', 
                            validation = 'no_text_validation', 
                            value = null, 
                            height = '', 
                            width = '', 
                            recipient_id = '', 
                            signing_elements_group_id = '', 
                            placeholder_name = '', 
                            options = [
                                signwell_sdk.models.document_response_fields_inner_inner_options_inner.DocumentResponse_fields_inner_inner_options_inner(
                                    name = '', 
                                    api_id = '', 
                                    is_other = True, )
                                ], 
                            default_option = '', 
                            allow_other = True, )
                        ]
                    ],
                allow_decline = True,
                allow_reassign = True,
                labels = [
                    signwell_sdk.models.label_info.LabelInfo(
                        id = '', 
                        name = '', )
                    ],
                checkbox_groups = [
                    signwell_sdk.models.checkbox_group_info.CheckboxGroupInfo(
                        id = '', 
                        group_name = '', 
                        recipient_id = '', 
                        checkbox_ids = [
                            ''
                            ], 
                        validation = 'minimum', 
                        required = True, 
                        min_value = 56, 
                        max_value = 56, 
                        exact_value = 56, )
                    ]
            )
        else:
            return DocumentResponse(
                test_mode = True,
                id = '',
        )
        """

    def testDocumentResponse(self):
        """Test DocumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
