# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create Webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete Webhook
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List Webhooks
        """
        pass


if __name__ == '__main__':
    unittest.main()
