# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.field_type import FieldType

class TestFieldType(unittest.TestCase):
    """FieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldType(self):
        """Test FieldType"""
        # inst = FieldType()

if __name__ == '__main__':
    unittest.main()
