# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.me_response import MeResponse

class TestMeResponse(unittest.TestCase):
    """MeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeResponse:
        """Test MeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeResponse`
        """
        model = MeResponse()
        if include_optional:
            return MeResponse(
                id = '',
                role = '',
                archived = True,
                user = signwell_sdk.models.me_response_user.MeResponse_user(
                    id = '', 
                    name = '', 
                    email = '', 
                    has_google_registration = True, 
                    first_name = '', 
                    preferences = signwell_sdk.models.me_response_user_preferences.MeResponse_user_preferences(
                        sales_document = True, 
                        time_zone = '', 
                        smart_fields = True, ), ),
                account = signwell_sdk.models.account_info_response.AccountInfoResponse(
                    id = '', 
                    name = '', 
                    plan_tier = '', 
                    active_templates = 56, 
                    can_create_template = True, 
                    can_create_tracking_document = True, 
                    can_create_completion_document = True, 
                    active_users = [
                        signwell_sdk.models.account_info_response_active_users_inner.AccountInfoResponse_active_users_inner(
                            id = '', 
                            name = '', 
                            email = '', 
                            has_google_registration = True, )
                        ], 
                    preferences = signwell_sdk.models.account_info_response_preferences.AccountInfoResponse_preferences(
                        date_format = '', 
                        days_until_links_expire = 56, 
                        disable_apply_everywhere = True, 
                        disable_apply_everywhere_effective = True, 
                        disable_drawn_signatures = True, 
                        disable_typed_signatures = True, 
                        disable_uploaded_signatures = True, 
                        enable_redirect = True, 
                        hide_document_id_in_audit = True, 
                        mute_branding = True, 
                        redirect_url = '', 
                        separate_audit_pdf = True, 
                        separate_completed_file = True, 
                        enable_nom151_compliance = True, ), ),
                workspace = signwell_sdk.models.account_info_response.AccountInfoResponse(
                    id = '', 
                    name = '', 
                    plan_tier = '', 
                    active_templates = 56, 
                    can_create_template = True, 
                    can_create_tracking_document = True, 
                    can_create_completion_document = True, 
                    active_users = [
                        signwell_sdk.models.account_info_response_active_users_inner.AccountInfoResponse_active_users_inner(
                            id = '', 
                            name = '', 
                            email = '', 
                            has_google_registration = True, )
                        ], 
                    preferences = signwell_sdk.models.account_info_response_preferences.AccountInfoResponse_preferences(
                        date_format = '', 
                        days_until_links_expire = 56, 
                        disable_apply_everywhere = True, 
                        disable_apply_everywhere_effective = True, 
                        disable_drawn_signatures = True, 
                        disable_typed_signatures = True, 
                        disable_uploaded_signatures = True, 
                        enable_redirect = True, 
                        hide_document_id_in_audit = True, 
                        mute_branding = True, 
                        redirect_url = '', 
                        separate_audit_pdf = True, 
                        separate_completed_file = True, 
                        enable_nom151_compliance = True, ), ),
                contact = signwell_sdk.models.me_response_contact.MeResponse_contact(
                    id = '', 
                    email = '', 
                    name = '', 
                    company_name = '', 
                    phone_number = '', 
                    alt_phone_number = '', 
                    website = '', 
                    initials = '', 
                    archived = True, )
            )
        else:
            return MeResponse(
                id = '',
                role = '',
                user = signwell_sdk.models.me_response_user.MeResponse_user(
                    id = '', 
                    name = '', 
                    email = '', 
                    has_google_registration = True, 
                    first_name = '', 
                    preferences = signwell_sdk.models.me_response_user_preferences.MeResponse_user_preferences(
                        sales_document = True, 
                        time_zone = '', 
                        smart_fields = True, ), ),
                account = signwell_sdk.models.account_info_response.AccountInfoResponse(
                    id = '', 
                    name = '', 
                    plan_tier = '', 
                    active_templates = 56, 
                    can_create_template = True, 
                    can_create_tracking_document = True, 
                    can_create_completion_document = True, 
                    active_users = [
                        signwell_sdk.models.account_info_response_active_users_inner.AccountInfoResponse_active_users_inner(
                            id = '', 
                            name = '', 
                            email = '', 
                            has_google_registration = True, )
                        ], 
                    preferences = signwell_sdk.models.account_info_response_preferences.AccountInfoResponse_preferences(
                        date_format = '', 
                        days_until_links_expire = 56, 
                        disable_apply_everywhere = True, 
                        disable_apply_everywhere_effective = True, 
                        disable_drawn_signatures = True, 
                        disable_typed_signatures = True, 
                        disable_uploaded_signatures = True, 
                        enable_redirect = True, 
                        hide_document_id_in_audit = True, 
                        mute_branding = True, 
                        redirect_url = '', 
                        separate_audit_pdf = True, 
                        separate_completed_file = True, 
                        enable_nom151_compliance = True, ), ),
                workspace = signwell_sdk.models.account_info_response.AccountInfoResponse(
                    id = '', 
                    name = '', 
                    plan_tier = '', 
                    active_templates = 56, 
                    can_create_template = True, 
                    can_create_tracking_document = True, 
                    can_create_completion_document = True, 
                    active_users = [
                        signwell_sdk.models.account_info_response_active_users_inner.AccountInfoResponse_active_users_inner(
                            id = '', 
                            name = '', 
                            email = '', 
                            has_google_registration = True, )
                        ], 
                    preferences = signwell_sdk.models.account_info_response_preferences.AccountInfoResponse_preferences(
                        date_format = '', 
                        days_until_links_expire = 56, 
                        disable_apply_everywhere = True, 
                        disable_apply_everywhere_effective = True, 
                        disable_drawn_signatures = True, 
                        disable_typed_signatures = True, 
                        disable_uploaded_signatures = True, 
                        enable_redirect = True, 
                        hide_document_id_in_audit = True, 
                        mute_branding = True, 
                        redirect_url = '', 
                        separate_audit_pdf = True, 
                        separate_completed_file = True, 
                        enable_nom151_compliance = True, ), ),
                contact = signwell_sdk.models.me_response_contact.MeResponse_contact(
                    id = '', 
                    email = '', 
                    name = '', 
                    company_name = '', 
                    phone_number = '', 
                    alt_phone_number = '', 
                    website = '', 
                    initials = '', 
                    archived = True, ),
        )
        """

    def testMeResponse(self):
        """Test MeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
