# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.account_info_response_active_users_inner import AccountInfoResponseActiveUsersInner

class TestAccountInfoResponseActiveUsersInner(unittest.TestCase):
    """AccountInfoResponseActiveUsersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfoResponseActiveUsersInner:
        """Test AccountInfoResponseActiveUsersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountInfoResponseActiveUsersInner`
        """
        model = AccountInfoResponseActiveUsersInner()
        if include_optional:
            return AccountInfoResponseActiveUsersInner(
                id = '',
                name = '',
                email = '',
                has_google_registration = True
            )
        else:
            return AccountInfoResponseActiveUsersInner(
                id = '',
                name = '',
                email = '',
        )
        """

    def testAccountInfoResponseActiveUsersInner(self):
        """Test AccountInfoResponseActiveUsersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
