# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.bulk_send_csv_template_response import BulkSendCsvTemplateResponse

class TestBulkSendCsvTemplateResponse(unittest.TestCase):
    """BulkSendCsvTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSendCsvTemplateResponse:
        """Test BulkSendCsvTemplateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSendCsvTemplateResponse`
        """
        model = BulkSendCsvTemplateResponse()
        if include_optional:
            return BulkSendCsvTemplateResponse(
                data = 'YQ=='
            )
        else:
            return BulkSendCsvTemplateResponse(
                data = 'YQ==',
        )
        """

    def testBulkSendCsvTemplateResponse(self):
        """Test BulkSendCsvTemplateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
