# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_response_recipients_inner import DocumentResponseRecipientsInner

class TestDocumentResponseRecipientsInner(unittest.TestCase):
    """DocumentResponseRecipientsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentResponseRecipientsInner:
        """Test DocumentResponseRecipientsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentResponseRecipientsInner`
        """
        model = DocumentResponseRecipientsInner()
        if include_optional:
            return DocumentResponseRecipientsInner(
                id = '',
                name = '',
                email = '',
                body = '',
                message = '',
                subject = '',
                send_email = True,
                send_email_delay = 56,
                signing_order = 56,
                signing_url = '',
                embedded_signing_url = '',
                bounced = True,
                bounced_details = '',
                attachment_requests = [
                    signwell_sdk.models.attachment_request_info.AttachmentRequestInfo(
                        name = '', 
                        url = '', 
                        required = True, )
                    ],
                passcode = '',
                status = ''
            )
        else:
            return DocumentResponseRecipientsInner(
                name = '',
                email = '',
        )
        """

    def testDocumentResponseRecipientsInner(self):
        """Test DocumentResponseRecipientsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
