# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.template_api import TemplateApi


class TestTemplateApi(unittest.TestCase):
    """TemplateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplateApi()

    def tearDown(self) -> None:
        pass

    def test_create_template(self) -> None:
        """Test case for create_template

        Create Template
        """
        pass

    def test_delete_template(self) -> None:
        """Test case for delete_template

        Delete Template
        """
        pass

    def test_get_template(self) -> None:
        """Test case for get_template

        Get Template
        """
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List Templates
        """
        pass

    def test_update_template(self) -> None:
        """Test case for update_template

        Update Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
