# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.update_recipients_request import UpdateRecipientsRequest

class TestUpdateRecipientsRequest(unittest.TestCase):
    """UpdateRecipientsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRecipientsRequest:
        """Test UpdateRecipientsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRecipientsRequest`
        """
        model = UpdateRecipientsRequest()
        if include_optional:
            return UpdateRecipientsRequest(
                recipients = [
                    signwell_sdk.models.update_recipients_map_inner.update_recipients_map_inner(
                        id = '', 
                        name = '', 
                        email = 'jane@example.com', 
                        subject = '', 
                        message = '', 
                        passcode = '', )
                    ]
            )
        else:
            return UpdateRecipientsRequest(
                recipients = [
                    signwell_sdk.models.update_recipients_map_inner.update_recipients_map_inner(
                        id = '', 
                        name = '', 
                        email = 'jane@example.com', 
                        subject = '', 
                        message = '', 
                        passcode = '', )
                    ],
        )
        """

    def testUpdateRecipientsRequest(self):
        """Test UpdateRecipientsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
