# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.bulk_send_csv_request import BulkSendCsvRequest

class TestBulkSendCsvRequest(unittest.TestCase):
    """BulkSendCsvRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSendCsvRequest:
        """Test BulkSendCsvRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSendCsvRequest`
        """
        model = BulkSendCsvRequest()
        if include_optional:
            return BulkSendCsvRequest(
                template_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
                bulk_send_csv = 'bmFtZSxlbWFpbApUZXN0LHRlc3RAZXhhbXBsZS5jb20K'
            )
        else:
            return BulkSendCsvRequest(
                template_ids = [
                    '00000000-0000-0000-0000-000000000000'
                    ],
                bulk_send_csv = 'bmFtZSxlbWFpbApUZXN0LHRlc3RAZXhhbXBsZS5jb20K',
        )
        """

    def testBulkSendCsvRequest(self):
        """Test BulkSendCsvRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
