# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.nom151_url_response import Nom151UrlResponse

class TestNom151UrlResponse(unittest.TestCase):
    """Nom151UrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Nom151UrlResponse:
        """Test Nom151UrlResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Nom151UrlResponse`
        """
        model = Nom151UrlResponse()
        if include_optional:
            return Nom151UrlResponse(
                file_url = ''
            )
        else:
            return Nom151UrlResponse(
                file_url = '',
        )
        """

    def testNom151UrlResponse(self):
        """Test Nom151UrlResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
