# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_template_response_placeholders_inner import DocumentTemplateResponsePlaceholdersInner

class TestDocumentTemplateResponsePlaceholdersInner(unittest.TestCase):
    """DocumentTemplateResponsePlaceholdersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentTemplateResponsePlaceholdersInner:
        """Test DocumentTemplateResponsePlaceholdersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentTemplateResponsePlaceholdersInner`
        """
        model = DocumentTemplateResponsePlaceholdersInner()
        if include_optional:
            return DocumentTemplateResponsePlaceholdersInner(
                id = '',
                name = '',
                subject = '',
                message = '',
                preassigned_recipient_name = '',
                preassigned_recipient_email = '',
                signing_order = 56,
                attachment_requests = [
                    signwell_sdk.models.attachment_request_info.AttachmentRequestInfo(
                        name = '', 
                        url = '', 
                        required = True, )
                    ]
            )
        else:
            return DocumentTemplateResponsePlaceholdersInner(
                name = '',
        )
        """

    def testDocumentTemplateResponsePlaceholdersInner(self):
        """Test DocumentTemplateResponsePlaceholdersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
