# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.me_response_user_preferences import MeResponseUserPreferences

class TestMeResponseUserPreferences(unittest.TestCase):
    """MeResponseUserPreferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeResponseUserPreferences:
        """Test MeResponseUserPreferences
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeResponseUserPreferences`
        """
        model = MeResponseUserPreferences()
        if include_optional:
            return MeResponseUserPreferences(
                sales_document = True,
                time_zone = '',
                smart_fields = True
            )
        else:
            return MeResponseUserPreferences(
        )
        """

    def testMeResponseUserPreferences(self):
        """Test MeResponseUserPreferences"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
