# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.date_format import DateFormat

class TestDateFormat(unittest.TestCase):
    """DateFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDateFormat(self):
        """Test DateFormat"""
        # inst = DateFormat()

if __name__ == '__main__':
    unittest.main()
