# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_response_fields_inner_inner import DocumentResponseFieldsInnerInner

class TestDocumentResponseFieldsInnerInner(unittest.TestCase):
    """DocumentResponseFieldsInnerInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentResponseFieldsInnerInner:
        """Test DocumentResponseFieldsInnerInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentResponseFieldsInnerInner`
        """
        model = DocumentResponseFieldsInnerInner()
        if include_optional:
            return DocumentResponseFieldsInnerInner(
                x = 1.337,
                y = 1.337,
                page = 56,
                recipient = signwell_sdk.models.document_response_fields_inner_inner_recipient.DocumentResponse_fields_inner_inner_recipient(
                    email = '', 
                    name = '', ),
                api_id = '',
                name = '',
                date_format = 'MM/DD/YYYY',
                fixed_width = True,
                formula = '',
                label = '',
                lock_sign_date = True,
                required = True,
                type = 'initials',
                validation = 'no_text_validation',
                value = None,
                height = '',
                width = '',
                recipient_id = '',
                signing_elements_group_id = '',
                placeholder_name = '',
                options = [
                    signwell_sdk.models.document_response_fields_inner_inner_options_inner.DocumentResponse_fields_inner_inner_options_inner(
                        name = '', 
                        api_id = '', 
                        is_other = True, )
                    ],
                default_option = '',
                allow_other = True
            )
        else:
            return DocumentResponseFieldsInnerInner(
                x = 1.337,
                y = 1.337,
                page = 56,
        )
        """

    def testDocumentResponseFieldsInnerInner(self):
        """Test DocumentResponseFieldsInnerInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
