# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.document_api import DocumentApi


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentApi()

    def tearDown(self) -> None:
        pass

    def test_create_document(self) -> None:
        """Test case for create_document

        Create Document
        """
        pass

    def test_create_document_from_template(self) -> None:
        """Test case for create_document_from_template

        Create Document from Template
        """
        pass

    def test_delete_document(self) -> None:
        """Test case for delete_document

        Delete Document
        """
        pass

    def test_get_completed_pdf(self) -> None:
        """Test case for get_completed_pdf

        Completed PDF
        """
        pass

    def test_get_document(self) -> None:
        """Test case for get_document

        Get Document
        """
        pass

    def test_list_documents(self) -> None:
        """Test case for list_documents

        List Documents
        """
        pass

    def test_send_document(self) -> None:
        """Test case for send_document

        Update and Send Document
        """
        pass

    def test_send_reminder(self) -> None:
        """Test case for send_reminder

        Send Reminder
        """
        pass

    def test_update_recipients(self) -> None:
        """Test case for update_recipients

        Update Recipients
        """
        pass


if __name__ == '__main__':
    unittest.main()
