# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.checkbox_validation import CheckboxValidation

class TestCheckboxValidation(unittest.TestCase):
    """CheckboxValidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckboxValidation(self):
        """Test CheckboxValidation"""
        # inst = CheckboxValidation()

if __name__ == '__main__':
    unittest.main()
