# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.nom151_certificate_response import Nom151CertificateResponse

class TestNom151CertificateResponse(unittest.TestCase):
    """Nom151CertificateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Nom151CertificateResponse:
        """Test Nom151CertificateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Nom151CertificateResponse`
        """
        model = Nom151CertificateResponse()
        if include_optional:
            return Nom151CertificateResponse(
                nom151 = signwell_sdk.models.nom151_certificate_response_nom151.Nom151CertificateResponse_nom151(
                    status = '', 
                    transaction_id = '', 
                    hash = '', 
                    folio = '', 
                    issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    provider = '', 
                    validation_url = '', 
                    constancia = '', )
            )
        else:
            return Nom151CertificateResponse(
                nom151 = signwell_sdk.models.nom151_certificate_response_nom151.Nom151CertificateResponse_nom151(
                    status = '', 
                    transaction_id = '', 
                    hash = '', 
                    folio = '', 
                    issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    provider = '', 
                    validation_url = '', 
                    constancia = '', ),
        )
        """

    def testNom151CertificateResponse(self):
        """Test Nom151CertificateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
