# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.fields_inner_inner import FieldsInnerInner

class TestFieldsInnerInner(unittest.TestCase):
    """FieldsInnerInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldsInnerInner:
        """Test FieldsInnerInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldsInnerInner`
        """
        model = FieldsInnerInner()
        if include_optional:
            return FieldsInnerInner(
                x = 1.337,
                y = 1.337,
                page = 56,
                recipient_id = '',
                type = 'initials',
                required = True,
                label = '',
                value = None,
                api_id = '',
                name = '',
                validation = 'no_text_validation',
                fixed_width = True,
                lock_sign_date = True,
                date_format = 'MM/DD/YYYY',
                height = 1.337,
                width = 1.337,
                options = [
                    null
                    ],
                default_option = '',
                allow_other = True
            )
        else:
            return FieldsInnerInner(
                x = 1.337,
                y = 1.337,
                page = 56,
                recipient_id = '',
                type = 'initials',
        )
        """

    def testFieldsInnerInner(self):
        """Test FieldsInnerInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
