# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.pagination_meta import PaginationMeta

class TestPaginationMeta(unittest.TestCase):
    """PaginationMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationMeta:
        """Test PaginationMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationMeta`
        """
        model = PaginationMeta()
        if include_optional:
            return PaginationMeta(
                current_page = 56,
                next_page = 56,
                previous_page = 56,
                total_count = 56,
                total_pages = 56
            )
        else:
            return PaginationMeta(
                current_page = 56,
                total_count = 56,
                total_pages = 56,
        )
        """

    def testPaginationMeta(self):
        """Test PaginationMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
