# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.api.regional_api import RegionalApi


class TestRegionalApi(unittest.TestCase):
    """RegionalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegionalApi()

    def tearDown(self) -> None:
        pass

    def test_get_nom151_certificate(self) -> None:
        """Test case for get_nom151_certificate

        MX – NOM-151 Certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
