# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_from_template_response_fields_inner_inner_recipient import DocumentFromTemplateResponseFieldsInnerInnerRecipient

class TestDocumentFromTemplateResponseFieldsInnerInnerRecipient(unittest.TestCase):
    """DocumentFromTemplateResponseFieldsInnerInnerRecipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentFromTemplateResponseFieldsInnerInnerRecipient:
        """Test DocumentFromTemplateResponseFieldsInnerInnerRecipient
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentFromTemplateResponseFieldsInnerInnerRecipient`
        """
        model = DocumentFromTemplateResponseFieldsInnerInnerRecipient()
        if include_optional:
            return DocumentFromTemplateResponseFieldsInnerInnerRecipient(
                email = '',
                name = '',
                role = ''
            )
        else:
            return DocumentFromTemplateResponseFieldsInnerInnerRecipient(
                email = '',
                name = '',
        )
        """

    def testDocumentFromTemplateResponseFieldsInnerInnerRecipient(self):
        """Test DocumentFromTemplateResponseFieldsInnerInnerRecipient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
