# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.completed_pdf_url_response import CompletedPdfUrlResponse

class TestCompletedPdfUrlResponse(unittest.TestCase):
    """CompletedPdfUrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompletedPdfUrlResponse:
        """Test CompletedPdfUrlResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompletedPdfUrlResponse`
        """
        model = CompletedPdfUrlResponse()
        if include_optional:
            return CompletedPdfUrlResponse(
                file_url = ''
            )
        else:
            return CompletedPdfUrlResponse(
                file_url = '',
        )
        """

    def testCompletedPdfUrlResponse(self):
        """Test CompletedPdfUrlResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
