# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.document_from_template_request import DocumentFromTemplateRequest

class TestDocumentFromTemplateRequest(unittest.TestCase):
    """DocumentFromTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentFromTemplateRequest:
        """Test DocumentFromTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentFromTemplateRequest`
        """
        model = DocumentFromTemplateRequest()
        if include_optional:
            return DocumentFromTemplateRequest(
                test_mode = True,
                template_id = '',
                template_ids = [
                    ''
                    ],
                name = '',
                subject = '',
                message = '',
                recipients = [
                    signwell_sdk.models.template_recipients_inner.TemplateRecipients_inner(
                        id = '', 
                        name = '', 
                        email = 'signer@example.com', 
                        placeholder_name = '', 
                        passcode = '', 
                        subject = '', 
                        message = '', 
                        send_email = True, 
                        send_email_delay = 56, )
                    ],
                exclude_placeholders = [
                    ''
                    ],
                draft = True,
                with_signature_page = True,
                expires_in = 1,
                reminders = True,
                apply_signing_order = True,
                api_application_id = '',
                embedded_signing = True,
                embedded_signing_notifications = True,
                text_tags = True,
                custom_requester_name = '',
                custom_requester_email = '',
                redirect_url = '',
                allow_decline = True,
                allow_reassign = True,
                decline_redirect_url = '',
                language = '',
                metadata = {
                    'key' : ''
                    },
                template_fields = [
                    signwell_sdk.models.template_field_values_inner.TemplateFieldValues_inner(
                        api_id = '', 
                        value = null, )
                    ],
                files = [
                    signwell_sdk.models.additional_files_inner.AdditionalFiles_inner(
                        name = '', 
                        file_url = '', 
                        file_base64 = 'YQ==', )
                    ],
                fields = [
                    [
                        signwell_sdk.models.additional_fields_inner_inner.AdditionalFields_inner_inner(
                            x = 1.337, 
                            y = 1.337, 
                            page = 56, 
                            recipient_id = '', 
                            type = 'initials', 
                            required = True, 
                            label = '', 
                            value = null, 
                            api_id = '', 
                            name = '', 
                            validation = 'no_text_validation', 
                            fixed_width = True, 
                            lock_sign_date = True, 
                            date_format = 'MM/DD/YYYY', 
                            formula = '', 
                            height = 1.337, 
                            width = 1.337, 
                            options = [
                                null
                                ], 
                            default_option = '', 
                            allow_other = True, )
                        ]
                    ],
                attachment_requests = [
                    signwell_sdk.models.attachment_requests_inner.AttachmentRequests_inner(
                        name = '', 
                        recipient_id = '', 
                        required = True, )
                    ],
                copied_contacts = [
                    signwell_sdk.models.copied_contacts_inner.CopiedContacts_inner(
                        name = '', 
                        email = '', )
                    ],
                labels = [
                    signwell_sdk.models.label_request.LabelRequest(
                        name = '', )
                    ],
                checkbox_groups = [
                    signwell_sdk.models.checkbox_groups_inner.CheckboxGroups_inner(
                        group_name = '', 
                        recipient_id = '', 
                        checkbox_ids = [
                            ''
                            ], 
                        validation = 'minimum', 
                        required = True, 
                        min_value = 56, 
                        max_value = 56, 
                        exact_value = 56, )
                    ]
            )
        else:
            return DocumentFromTemplateRequest(
                recipients = [
                    signwell_sdk.models.template_recipients_inner.TemplateRecipients_inner(
                        id = '', 
                        name = '', 
                        email = 'signer@example.com', 
                        placeholder_name = '', 
                        passcode = '', 
                        subject = '', 
                        message = '', 
                        send_email = True, 
                        send_email_delay = 56, )
                    ],
        )
        """

    def testDocumentFromTemplateRequest(self):
        """Test DocumentFromTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
