# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.nom151_certificate_response_nom151 import Nom151CertificateResponseNom151

class TestNom151CertificateResponseNom151(unittest.TestCase):
    """Nom151CertificateResponseNom151 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Nom151CertificateResponseNom151:
        """Test Nom151CertificateResponseNom151
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Nom151CertificateResponseNom151`
        """
        model = Nom151CertificateResponseNom151()
        if include_optional:
            return Nom151CertificateResponseNom151(
                status = '',
                transaction_id = '',
                hash = '',
                folio = '',
                issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                provider = '',
                validation_url = '',
                constancia = ''
            )
        else:
            return Nom151CertificateResponseNom151(
                status = '',
                transaction_id = '',
                hash = '',
                folio = '',
                issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                provider = '',
                validation_url = '',
                constancia = '',
        )
        """

    def testNom151CertificateResponseNom151(self):
        """Test Nom151CertificateResponseNom151"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
