# coding: utf-8

"""
    SignWell Developer API

    API for creating, managing, and tracking electronic signature workflows.

    The version of the OpenAPI document: v1
    Contact: support@signwell.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from signwell_sdk.models.file_format import FileFormat

class TestFileFormat(unittest.TestCase):
    """FileFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileFormat(self):
        """Test FileFormat"""
        # inst = FileFormat()

if __name__ == '__main__':
    unittest.main()
