"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt, StrictBool
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated
from signwell_sdk.models.nom151_url_response import Nom151UrlResponse
from signwell_sdk.models.nom151_certificate_response import Nom151CertificateResponse
from signwell_sdk.api_client import ApiClient, RequestSerialized
from signwell_sdk.api_response import ApiResponse
from signwell_sdk.rest import RESTResponseType


class RegionalApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_nom151_certificate(
        self,
        id: StrictStr,
        url_only: Annotated[
            StrictBool | None,
            Field(description="If true, returns JSON with download URL instead of downloading the file"),
        ] = None,
        object_only: StrictBool | None = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: Dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytes | Nom151UrlResponse | Nom151CertificateResponse:
        """MX – NOM-151 Certificate

        Download NOM-151 certificate for a completed document. Returns a ZIP file, download URL, or raw certificate data based on query parameters.

        :param id: (required)
        :type id: str
        :param url_only: If true, returns JSON with download URL instead of downloading the file
        :type url_only: bool
        :param object_only:
        :type object_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501
        if url_only is True and object_only is True:
            raise ValueError("get_nom151_certificate does not support url_only and object_only together.")

        _param = self._get_nom151_certificate_serialize(
            id=id,
            url_only=url_only,
            object_only=object_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )
        if url_only is True:
            _return_type = "Nom151UrlResponse"
        elif object_only is True:
            _return_type = "Nom151CertificateResponse"
        else:
            _return_type = "bytes"

        _response_types_map: Dict[str, str | None] = {
            "200": "Nom151UrlResponse",
            "404": "ErrorResponse",
            "422": "ValidationErrorResponse",
            "429": "RateLimitErrorResponse",
        }
        _response_types_map["200"] = _return_type

        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_nom151_certificate_with_http_info(
        self,
        id: StrictStr,
        url_only: Annotated[
            StrictBool | None,
            Field(description="If true, returns JSON with download URL instead of downloading the file"),
        ] = None,
        object_only: StrictBool | None = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: Dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytes | Nom151UrlResponse | Nom151CertificateResponse]:
        """MX – NOM-151 Certificate

        Download NOM-151 certificate for a completed document. Returns a ZIP file, download URL, or raw certificate data based on query parameters.

        :param id: (required)
        :type id: str
        :param url_only: If true, returns JSON with download URL instead of downloading the file
        :type url_only: bool
        :param object_only:
        :type object_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501
        if url_only is True and object_only is True:
            raise ValueError("get_nom151_certificate does not support url_only and object_only together.")

        _param = self._get_nom151_certificate_serialize(
            id=id,
            url_only=url_only,
            object_only=object_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )
        if url_only is True:
            _return_type = "Nom151UrlResponse"
        elif object_only is True:
            _return_type = "Nom151CertificateResponse"
        else:
            _return_type = "bytes"

        _response_types_map: Dict[str, str | None] = {
            "200": "Nom151UrlResponse",
            "404": "ErrorResponse",
            "422": "ValidationErrorResponse",
            "429": "RateLimitErrorResponse",
        }
        _response_types_map["200"] = _return_type

        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_nom151_certificate_without_preload_content(
        self,
        id: StrictStr,
        url_only: Annotated[
            StrictBool | None,
            Field(description="If true, returns JSON with download URL instead of downloading the file"),
        ] = None,
        object_only: StrictBool | None = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: Dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """MX – NOM-151 Certificate

        Download NOM-151 certificate for a completed document. Returns a ZIP file, download URL, or raw certificate data based on query parameters.

        :param id: (required)
        :type id: str
        :param url_only: If true, returns JSON with download URL instead of downloading the file
        :type url_only: bool
        :param object_only:
        :type object_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501
        if url_only is True and object_only is True:
            raise ValueError("get_nom151_certificate does not support url_only and object_only together.")

        _param = self._get_nom151_certificate_serialize(
            id=id,
            url_only=url_only,
            object_only=object_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )
        if url_only is True:
            _return_type = "Nom151UrlResponse"
        elif object_only is True:
            _return_type = "Nom151CertificateResponse"
        else:
            _return_type = "bytes"

        _response_types_map: Dict[str, str | None] = {
            "200": "Nom151UrlResponse",
            "404": "ErrorResponse",
            "422": "ValidationErrorResponse",
            "429": "RateLimitErrorResponse",
        }
        _response_types_map["200"] = _return_type

        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_nom151_certificate_serialize(
        self,
        id,
        url_only,
        object_only,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, str | None] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: bytes | None = None

        # process the path parameters
        if id is not None:
            _path_params["id"] = id
        # process the query parameters
        if url_only is not None:
            _query_params.append(("url_only", url_only))

        if object_only is not None:
            _query_params.append(("object_only", object_only))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            if url_only is True or object_only is True:
                _header_params["Accept"] = "application/json"
            else:
                _header_params["Accept"] = "application/octet-stream"

        # authentication setting
        _auth_settings: List[str] = ["api_key"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/documents/{id}/nom151_certificate",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
