# coding: utf-8

# flake8: noqa

"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from types import SimpleNamespace

__version__ = "0.1.0"

# import apis into sdk package
from signwell_sdk.api.api_application_api import ApiApplicationApi
from signwell_sdk.api.bulk_send_api import BulkSendApi
from signwell_sdk.api.document_api import DocumentApi
from signwell_sdk.api.me_api import MeApi
from signwell_sdk.api.regional_api import RegionalApi
from signwell_sdk.api.template_api import TemplateApi
from signwell_sdk.api.webhooks_api import WebhooksApi

# import ApiClient
from signwell_sdk.api_response import ApiResponse
from signwell_sdk.api_client import ApiClient
from signwell_sdk.configuration import Configuration
from signwell_sdk.exceptions import OpenApiException
from signwell_sdk.exceptions import ApiTypeError
from signwell_sdk.exceptions import ApiValueError
from signwell_sdk.exceptions import ApiKeyError
from signwell_sdk.exceptions import ApiAttributeError
from signwell_sdk.exceptions import ApiException
from signwell_sdk.exceptions import ApiError
from signwell_sdk.exceptions import ApiConnectionError
from signwell_sdk.exceptions import ApiTimeoutError
from signwell_sdk.exceptions import AuthenticationError
from signwell_sdk.exceptions import BadRequestError
from signwell_sdk.exceptions import ConflictError
from signwell_sdk.exceptions import FetchError
from signwell_sdk.exceptions import ForbiddenError
from signwell_sdk.exceptions import InternalServerError
from signwell_sdk.exceptions import NotFoundError
from signwell_sdk.exceptions import PermissionDeniedError
from signwell_sdk.exceptions import RateLimitError
from signwell_sdk.exceptions import RequiredError
from signwell_sdk.exceptions import TransportError
from signwell_sdk.exceptions import UnprocessableEntityError
from signwell_sdk.exceptions import UnsupportedContentTypeError

# import models into sdk package
from signwell_sdk.models.account_info_response import AccountInfoResponse
from signwell_sdk.models.account_info_response_active_users_inner import AccountInfoResponseActiveUsersInner
from signwell_sdk.models.account_info_response_preferences import AccountInfoResponsePreferences
from signwell_sdk.models.additional_fields_inner_inner import AdditionalFieldsInnerInner
from signwell_sdk.models.additional_fields_inner_inner_value import AdditionalFieldsInnerInnerValue
from signwell_sdk.models.additional_files_inner import AdditionalFilesInner
from signwell_sdk.models.api_application_response import ApiApplicationResponse
from signwell_sdk.models.api_application_response_owner import ApiApplicationResponseOwner
from signwell_sdk.models.api_application_response_preferences import ApiApplicationResponsePreferences
from signwell_sdk.models.attachment_request_info import AttachmentRequestInfo
from signwell_sdk.models.attachment_requests_inner import AttachmentRequestsInner
from signwell_sdk.models.bulk_send_create_response import BulkSendCreateResponse
from signwell_sdk.models.bulk_send_csv_request import BulkSendCsvRequest
from signwell_sdk.models.bulk_send_csv_template_response import BulkSendCsvTemplateResponse
from signwell_sdk.models.bulk_send_documents_response import BulkSendDocumentsResponse
from signwell_sdk.models.bulk_send_list_item import BulkSendListItem
from signwell_sdk.models.bulk_send_list_response import BulkSendListResponse
from signwell_sdk.models.bulk_send_response import BulkSendResponse
from signwell_sdk.models.bulk_send_response_templates_inner import BulkSendResponseTemplatesInner
from signwell_sdk.models.bulk_send_validate_csv_response import BulkSendValidateCsvResponse
from signwell_sdk.models.checkbox_group_info import CheckboxGroupInfo
from signwell_sdk.models.checkbox_groups_inner import CheckboxGroupsInner
from signwell_sdk.models.checkbox_validation import CheckboxValidation
from signwell_sdk.models.completed_pdf_response import CompletedPdfResponse
from signwell_sdk.models.completed_pdf_url_response import CompletedPdfUrlResponse
from signwell_sdk.models.copied_contact_info import CopiedContactInfo
from signwell_sdk.models.copied_contacts_inner import CopiedContactsInner
from signwell_sdk.models.copied_placeholders_inner import CopiedPlaceholdersInner
from signwell_sdk.models.create_bulk_send_request import CreateBulkSendRequest
from signwell_sdk.models.create_webhook_request import CreateWebhookRequest
from signwell_sdk.models.date_format import DateFormat
from signwell_sdk.models.detailed_option import DetailedOption
from signwell_sdk.models.document_from_template_request import DocumentFromTemplateRequest
from signwell_sdk.models.document_from_template_response import DocumentFromTemplateResponse
from signwell_sdk.models.document_from_template_response_fields_inner_inner import (
    DocumentFromTemplateResponseFieldsInnerInner,
)
from signwell_sdk.models.document_from_template_response_fields_inner_inner_recipient import (
    DocumentFromTemplateResponseFieldsInnerInnerRecipient,
)
from signwell_sdk.models.document_from_template_response_recipients_inner import (
    DocumentFromTemplateResponseRecipientsInner,
)
from signwell_sdk.models.document_list_response import DocumentListResponse
from signwell_sdk.models.document_request import DocumentRequest
from signwell_sdk.models.document_response import DocumentResponse
from signwell_sdk.models.document_response_attachment_requests_inner import DocumentResponseAttachmentRequestsInner
from signwell_sdk.models.document_response_fields_inner_inner import DocumentResponseFieldsInnerInner
from signwell_sdk.models.document_response_fields_inner_inner_options_inner import (
    DocumentResponseFieldsInnerInnerOptionsInner,
)
from signwell_sdk.models.document_response_fields_inner_inner_recipient import DocumentResponseFieldsInnerInnerRecipient
from signwell_sdk.models.document_response_fields_inner_inner_value import DocumentResponseFieldsInnerInnerValue
from signwell_sdk.models.document_response_recipients_inner import DocumentResponseRecipientsInner
from signwell_sdk.models.document_template_list_response import DocumentTemplateListResponse
from signwell_sdk.models.document_template_request import DocumentTemplateRequest
from signwell_sdk.models.document_template_response import DocumentTemplateResponse
from signwell_sdk.models.document_template_response_copied_placeholders_inner import (
    DocumentTemplateResponseCopiedPlaceholdersInner,
)
from signwell_sdk.models.document_template_response_placeholders_inner import DocumentTemplateResponsePlaceholdersInner
from signwell_sdk.models.document_template_update_request import DocumentTemplateUpdateRequest
from signwell_sdk.models.dropdown_option import DropdownOption
from signwell_sdk.models.error_response import ErrorResponse
from signwell_sdk.models.error_response_meta import ErrorResponseMeta
from signwell_sdk.models.field_type import FieldType
from signwell_sdk.models.fields_inner_inner import FieldsInnerInner
from signwell_sdk.models.file_format import FileFormat
from signwell_sdk.models.file_info import FileInfo
from signwell_sdk.models.files_inner import FilesInner
from signwell_sdk.models.label_info import LabelInfo
from signwell_sdk.models.label_request import LabelRequest
from signwell_sdk.models.label_response import LabelResponse
from signwell_sdk.models.me_response import MeResponse
from signwell_sdk.models.me_response_contact import MeResponseContact
from signwell_sdk.models.me_response_user import MeResponseUser
from signwell_sdk.models.me_response_user_preferences import MeResponseUserPreferences
from signwell_sdk.models.nom151_certificate_response import Nom151CertificateResponse
from signwell_sdk.models.nom151_certificate_response_nom151 import Nom151CertificateResponseNom151
from signwell_sdk.models.nom151_url_response import Nom151UrlResponse
from signwell_sdk.models.pagination_meta import PaginationMeta
from signwell_sdk.models.placeholders_inner import PlaceholdersInner
from signwell_sdk.models.rate_limit_error_response import RateLimitErrorResponse
from signwell_sdk.models.recipients_inner import RecipientsInner
from signwell_sdk.models.reminder_recipients_inner import ReminderRecipientsInner
from signwell_sdk.models.send_reminder_request import SendReminderRequest
from signwell_sdk.models.template_attachment_requests_inner import TemplateAttachmentRequestsInner
from signwell_sdk.models.template_checkbox_groups_inner import TemplateCheckboxGroupsInner
from signwell_sdk.models.template_field_values_inner import TemplateFieldValuesInner
from signwell_sdk.models.template_field_values_inner_value import TemplateFieldValuesInnerValue
from signwell_sdk.models.template_fields_inner_inner import TemplateFieldsInnerInner
from signwell_sdk.models.template_recipients_inner import TemplateRecipientsInner
from signwell_sdk.models.text_validation import TextValidation
from signwell_sdk.models.update_document_and_send_request import UpdateDocumentAndSendRequest
from signwell_sdk.models.update_recipients_map_inner import UpdateRecipientsMapInner
from signwell_sdk.models.update_recipients_request import UpdateRecipientsRequest
from signwell_sdk.models.validation_error_response import ValidationErrorResponse
from signwell_sdk.models.webhook_response import WebhookResponse

from signwell_sdk import embedded as Embedded
from signwell_sdk import webhook as Webhook
from signwell_sdk.embedded import create_requesting_document
from signwell_sdk.embedded import create_signing_document
from signwell_sdk.embedded import create_signing_document_from_template
from signwell_sdk.embedded import embedded_signing_url
from signwell_sdk.embedded import embedded_signing_urls
from signwell_sdk.embedded import requesting_iframe
from signwell_sdk.embedded import script_tag
from signwell_sdk.embedded import signing_iframe

Resources = SimpleNamespace(
    ApiApplicationApi=ApiApplicationApi,
    BulkSendApi=BulkSendApi,
    DocumentApi=DocumentApi,
    MeApi=MeApi,
    RegionalApi=RegionalApi,
    TemplateApi=TemplateApi,
    WebhooksApi=WebhooksApi,
)

Models = SimpleNamespace(
    AccountInfoResponse=AccountInfoResponse,
    AccountInfoResponseActiveUsersInner=AccountInfoResponseActiveUsersInner,
    AccountInfoResponsePreferences=AccountInfoResponsePreferences,
    AdditionalFieldsInnerInner=AdditionalFieldsInnerInner,
    AdditionalFieldsInnerInnerValue=AdditionalFieldsInnerInnerValue,
    AdditionalFilesInner=AdditionalFilesInner,
    ApiApplicationResponse=ApiApplicationResponse,
    ApiApplicationResponseOwner=ApiApplicationResponseOwner,
    ApiApplicationResponsePreferences=ApiApplicationResponsePreferences,
    AttachmentRequestInfo=AttachmentRequestInfo,
    AttachmentRequestsInner=AttachmentRequestsInner,
    BulkSendCreateResponse=BulkSendCreateResponse,
    BulkSendCsvRequest=BulkSendCsvRequest,
    BulkSendCsvTemplateResponse=BulkSendCsvTemplateResponse,
    BulkSendDocumentsResponse=BulkSendDocumentsResponse,
    BulkSendListItem=BulkSendListItem,
    BulkSendListResponse=BulkSendListResponse,
    BulkSendResponse=BulkSendResponse,
    BulkSendResponseTemplatesInner=BulkSendResponseTemplatesInner,
    BulkSendValidateCsvResponse=BulkSendValidateCsvResponse,
    CheckboxGroupInfo=CheckboxGroupInfo,
    CheckboxGroupsInner=CheckboxGroupsInner,
    CheckboxValidation=CheckboxValidation,
    CompletedPdfResponse=CompletedPdfResponse,
    CompletedPdfUrlResponse=CompletedPdfUrlResponse,
    CopiedContactInfo=CopiedContactInfo,
    CopiedContactsInner=CopiedContactsInner,
    CopiedPlaceholdersInner=CopiedPlaceholdersInner,
    CreateBulkSendRequest=CreateBulkSendRequest,
    CreateWebhookRequest=CreateWebhookRequest,
    DateFormat=DateFormat,
    DetailedOption=DetailedOption,
    DocumentFromTemplateRequest=DocumentFromTemplateRequest,
    DocumentFromTemplateResponse=DocumentFromTemplateResponse,
    DocumentFromTemplateResponseFieldsInnerInner=DocumentFromTemplateResponseFieldsInnerInner,
    DocumentFromTemplateResponseFieldsInnerInnerRecipient=DocumentFromTemplateResponseFieldsInnerInnerRecipient,
    DocumentFromTemplateResponseRecipientsInner=DocumentFromTemplateResponseRecipientsInner,
    DocumentListResponse=DocumentListResponse,
    DocumentRequest=DocumentRequest,
    DocumentResponse=DocumentResponse,
    DocumentResponseAttachmentRequestsInner=DocumentResponseAttachmentRequestsInner,
    DocumentResponseFieldsInnerInner=DocumentResponseFieldsInnerInner,
    DocumentResponseFieldsInnerInnerOptionsInner=DocumentResponseFieldsInnerInnerOptionsInner,
    DocumentResponseFieldsInnerInnerRecipient=DocumentResponseFieldsInnerInnerRecipient,
    DocumentResponseFieldsInnerInnerValue=DocumentResponseFieldsInnerInnerValue,
    DocumentResponseRecipientsInner=DocumentResponseRecipientsInner,
    DocumentTemplateListResponse=DocumentTemplateListResponse,
    DocumentTemplateRequest=DocumentTemplateRequest,
    DocumentTemplateResponse=DocumentTemplateResponse,
    DocumentTemplateResponseCopiedPlaceholdersInner=DocumentTemplateResponseCopiedPlaceholdersInner,
    DocumentTemplateResponsePlaceholdersInner=DocumentTemplateResponsePlaceholdersInner,
    DocumentTemplateUpdateRequest=DocumentTemplateUpdateRequest,
    DropdownOption=DropdownOption,
    ErrorResponse=ErrorResponse,
    ErrorResponseMeta=ErrorResponseMeta,
    FieldType=FieldType,
    FieldsInnerInner=FieldsInnerInner,
    FileFormat=FileFormat,
    FileInfo=FileInfo,
    FilesInner=FilesInner,
    LabelInfo=LabelInfo,
    LabelRequest=LabelRequest,
    LabelResponse=LabelResponse,
    MeResponse=MeResponse,
    MeResponseContact=MeResponseContact,
    MeResponseUser=MeResponseUser,
    MeResponseUserPreferences=MeResponseUserPreferences,
    Nom151CertificateResponse=Nom151CertificateResponse,
    Nom151CertificateResponseNom151=Nom151CertificateResponseNom151,
    Nom151UrlResponse=Nom151UrlResponse,
    PaginationMeta=PaginationMeta,
    PlaceholdersInner=PlaceholdersInner,
    RateLimitErrorResponse=RateLimitErrorResponse,
    RecipientsInner=RecipientsInner,
    ReminderRecipientsInner=ReminderRecipientsInner,
    SendReminderRequest=SendReminderRequest,
    TemplateAttachmentRequestsInner=TemplateAttachmentRequestsInner,
    TemplateCheckboxGroupsInner=TemplateCheckboxGroupsInner,
    TemplateFieldValuesInner=TemplateFieldValuesInner,
    TemplateFieldValuesInnerValue=TemplateFieldValuesInnerValue,
    TemplateFieldsInnerInner=TemplateFieldsInnerInner,
    TemplateRecipientsInner=TemplateRecipientsInner,
    TextValidation=TextValidation,
    UpdateDocumentAndSendRequest=UpdateDocumentAndSendRequest,
    UpdateRecipientsMapInner=UpdateRecipientsMapInner,
    UpdateRecipientsRequest=UpdateRecipientsRequest,
    ValidationErrorResponse=ValidationErrorResponse,
    WebhookResponse=WebhookResponse,
)

Errors = SimpleNamespace(
    ApiError=ApiError,
    ApiException=ApiException,
    BadRequestError=BadRequestError,
    AuthenticationError=AuthenticationError,
    PermissionDeniedError=PermissionDeniedError,
    ForbiddenError=ForbiddenError,
    NotFoundError=NotFoundError,
    ConflictError=ConflictError,
    UnprocessableEntityError=UnprocessableEntityError,
    RateLimitError=RateLimitError,
    InternalServerError=InternalServerError,
    ApiConnectionError=ApiConnectionError,
    ApiTimeoutError=ApiTimeoutError,
    FetchError=FetchError,
    RequiredError=RequiredError,
    TransportError=TransportError,
    UnsupportedContentTypeError=UnsupportedContentTypeError,
)
