"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from dataclasses import dataclass
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from typing import Any, NoReturn, Optional


@dataclass(frozen=True)
class RateLimitInfo:
    limit: float | None = None
    remaining: float | None = None
    reset: float | None = None
    reset_at: datetime | None = None
    retry_after: float | None = None
    retry_after_at: datetime | None = None


class OpenApiException(Exception):
    """Base exception class for generated SDK errors."""


class ApiTypeError(OpenApiException, TypeError):
    def __init__(self, msg, path_to_item=None, valid_classes=None, key_type=None) -> None:
        self.path_to_item = path_to_item
        self.valid_classes = valid_classes
        self.key_type = key_type
        full_msg = msg
        if path_to_item:
            full_msg = f"{msg} at {render_path(path_to_item)}"
        super().__init__(full_msg)


class ApiValueError(OpenApiException, ValueError):
    def __init__(self, msg, path_to_item=None) -> None:
        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f"{msg} at {render_path(path_to_item)}"
        super().__init__(full_msg)


class ApiAttributeError(OpenApiException, AttributeError):
    def __init__(self, msg, path_to_item=None) -> None:
        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f"{msg} at {render_path(path_to_item)}"
        super().__init__(full_msg)


class ApiKeyError(OpenApiException, KeyError):
    def __init__(self, msg, path_to_item=None) -> None:
        self.path_to_item = path_to_item
        full_msg = msg
        if path_to_item:
            full_msg = f"{msg} at {render_path(path_to_item)}"
        super().__init__(full_msg)


class ApiException(OpenApiException):
    _SENSITIVE_HEADER_NAMES = {
        "authorization",
        "cookie",
        "proxy-authorization",
        "set-cookie",
        "x-api-key",
    }

    def __init__(
        self,
        status=None,
        reason=None,
        http_resp=None,
        *,
        body: str | None = None,
        data: Any | None = None,
    ) -> None:
        self.status = status
        self.reason = reason
        self.body = body
        self.data = data
        self.headers = None

        if http_resp:
            if self.status is None:
                self.status = http_resp.status
            if self.reason is None:
                self.reason = http_resp.reason
            if self.body is None:
                response_data = getattr(http_resp, "data", None)
                if isinstance(response_data, bytes):
                    try:
                        self.body = response_data.decode("utf-8")
                    except UnicodeDecodeError:
                        self.body = None
                elif isinstance(response_data, str):
                    self.body = response_data
            self.headers = http_resp.getheaders()
        self.rate_limit = extract_rate_limit_info(self.headers)

    @classmethod
    def _redacted_headers(cls, headers):
        if headers is None:
            return None
        try:
            items = headers.items()
        except AttributeError:
            try:
                items = list(headers)
            except TypeError:
                return headers
        redacted = {}
        for name, value in items:
            if str(name).lower() in cls._SENSITIVE_HEADER_NAMES:
                redacted[name] = "[REDACTED]"
            else:
                redacted[name] = value
        return redacted

    def __str__(self):
        error_message = f"({self.status})\nReason: {self.reason}\n"
        redacted_headers = self._redacted_headers(self.headers)
        if redacted_headers:
            error_message += f"HTTP response headers: {redacted_headers}\n"
        if self.data or self.body:
            error_message += "HTTP response body/data omitted; inspect exc.body or exc.data explicitly.\n"
        return error_message

    @classmethod
    def from_response(
        cls,
        *,
        http_resp,
        body: str | None,
        data: Any | None,
    ) -> NoReturn:
        status = http_resp.status
        if status == 400:
            raise BadRequestError(http_resp=http_resp, body=body, data=data)
        if status == 401:
            raise AuthenticationError(http_resp=http_resp, body=body, data=data)
        if status == 403:
            raise PermissionDeniedError(http_resp=http_resp, body=body, data=data)
        if status == 404:
            raise NotFoundError(http_resp=http_resp, body=body, data=data)
        if status == 409:
            raise ConflictError(http_resp=http_resp, body=body, data=data)
        if status == 422:
            raise UnprocessableEntityError(http_resp=http_resp, body=body, data=data)
        if status == 429:
            raise RateLimitError(http_resp=http_resp, body=body, data=data)
        if 500 <= status <= 599:
            raise InternalServerError(http_resp=http_resp, body=body, data=data)
        raise ApiException(http_resp=http_resp, body=body, data=data)


class ApiError(ApiException):
    """Base class for SignWell API response errors."""


class BadRequestError(ApiError):
    pass


class AuthenticationError(ApiError):
    pass


class PermissionDeniedError(ApiError):
    pass


class NotFoundError(ApiError):
    pass


class ConflictError(ApiError):
    pass


class UnprocessableEntityError(ApiError):
    pass


class RateLimitError(ApiError):
    pass


class InternalServerError(ApiError):
    pass


class ApiConnectionError(ApiException):
    """Raised for network transport failures before a response is available."""


class ApiTimeoutError(ApiConnectionError):
    """Raised when urllib3 times out before receiving a complete response."""


class FetchError(ApiConnectionError):
    """Compatibility class for fetch-style transport failures."""


class RequiredError(ApiValueError):
    """Raised when a required API parameter is missing."""

    def __init__(self, field: str, message: str | None = None) -> None:
        self.field = field
        super().__init__(message or f'Required parameter "{field}" was null or undefined.')


class UnsupportedContentTypeError(ApiException):
    """Raised when a JSON model response uses an unsupported content type."""


# Backward-compatible SignWell aliases.
ForbiddenError = PermissionDeniedError
TransportError = ApiConnectionError

# OpenAPI Generator compatibility aliases.
BadRequestException = BadRequestError
UnauthorizedException = AuthenticationError
ForbiddenException = ForbiddenError
NotFoundException = NotFoundError
ConflictException = ConflictError
UnprocessableEntityException = UnprocessableEntityError
ServiceException = InternalServerError


def extract_rate_limit_info(headers: Any) -> RateLimitInfo | None:
    limit = _parse_number(_first_header(headers, ["x-ratelimit-limit", "ratelimit-limit"]))
    remaining = _parse_number(_first_header(headers, ["x-ratelimit-remaining", "ratelimit-remaining"]))
    reset = _parse_number(_first_header(headers, ["x-ratelimit-reset", "ratelimit-reset"]))
    retry_after_value = _first_header(headers, ["retry-after"])
    retry_after = _parse_number(retry_after_value)
    retry_after_at = None if retry_after is not None else _parse_datetime(retry_after_value)
    reset_at = datetime.fromtimestamp(reset, tz=timezone.utc) if reset is not None and reset > 1_000_000_000 else None

    if all(value is None for value in (limit, remaining, reset, retry_after, retry_after_at)):
        return None

    return RateLimitInfo(
        limit=limit,
        remaining=remaining,
        reset=reset,
        reset_at=reset_at,
        retry_after=retry_after,
        retry_after_at=retry_after_at,
    )


def _first_header(headers: Any, names: list[str]) -> str | None:
    if headers is None:
        return None
    try:
        items = headers.items()
    except AttributeError:
        try:
            items = list(headers)
        except TypeError:
            return None

    lowered = {name.lower() for name in names}
    for name, value in items:
        if str(name).lower() not in lowered:
            continue
        values = value if isinstance(value, list | tuple) else [value]
        for item in values:
            if isinstance(item, str) and item.strip():
                return item
    return None


def _parse_number(value: str | None) -> float | None:
    if value is None:
        return None
    token = value.strip().split(",", maxsplit=1)[0].split(";", maxsplit=1)[0].strip()
    try:
        return float(token)
    except ValueError:
        return None


def _parse_datetime(value: str | None) -> datetime | None:
    if value is None:
        return None
    try:
        parsed = parsedate_to_datetime(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=timezone.utc)


def render_path(path_to_item):
    """Returns a string representation of a path."""
    result = ""
    for pth in path_to_item:
        if isinstance(pth, int):
            result += f"[{pth}]"
        else:
            result += f"['{pth}']"
    return result
