"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Any, Optional, Set
from typing_extensions import Self


class AccountInfoResponsePreferences(BaseModel):
    """
    AccountInfoResponsePreferences
    """  # noqa: E501

    date_format: StrictStr | None = None
    days_until_links_expire: StrictInt | None = None
    disable_apply_everywhere: StrictBool | None = None
    disable_apply_everywhere_effective: StrictBool | None = None
    disable_drawn_signatures: StrictBool | None = None
    disable_typed_signatures: StrictBool | None = None
    disable_uploaded_signatures: StrictBool | None = None
    enable_redirect: StrictBool | None = None
    hide_document_id_in_audit: StrictBool | None = None
    mute_branding: StrictBool | None = None
    redirect_url: StrictStr | None = None
    separate_audit_pdf: StrictBool | None = None
    separate_completed_file: StrictBool | None = None
    enable_nom151_compliance: StrictBool | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "date_format",
        "days_until_links_expire",
        "disable_apply_everywhere",
        "disable_apply_everywhere_effective",
        "disable_drawn_signatures",
        "disable_typed_signatures",
        "disable_uploaded_signatures",
        "enable_redirect",
        "hide_document_id_in_audit",
        "mute_branding",
        "redirect_url",
        "separate_audit_pdf",
        "separate_completed_file",
        "enable_nom151_compliance",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AccountInfoResponsePreferences from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_url is None and "redirect_url" in self.model_fields_set:
            _dict["redirect_url"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of AccountInfoResponsePreferences from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "date_format": obj.get("date_format"),
                "days_until_links_expire": obj.get("days_until_links_expire"),
                "disable_apply_everywhere": obj.get("disable_apply_everywhere"),
                "disable_apply_everywhere_effective": obj.get("disable_apply_everywhere_effective"),
                "disable_drawn_signatures": obj.get("disable_drawn_signatures"),
                "disable_typed_signatures": obj.get("disable_typed_signatures"),
                "disable_uploaded_signatures": obj.get("disable_uploaded_signatures"),
                "enable_redirect": obj.get("enable_redirect"),
                "hide_document_id_in_audit": obj.get("hide_document_id_in_audit"),
                "mute_branding": obj.get("mute_branding"),
                "redirect_url": obj.get("redirect_url"),
                "separate_audit_pdf": obj.get("separate_audit_pdf"),
                "separate_completed_file": obj.get("separate_completed_file"),
                "enable_nom151_compliance": obj.get("enable_nom151_compliance"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
