"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.api_application_response_owner import ApiApplicationResponseOwner
from signwell_sdk.models.api_application_response_preferences import ApiApplicationResponsePreferences
from typing import Any, Optional, Set
from typing_extensions import Self


class ApiApplicationResponse(BaseModel):
    """
    API application details
    """  # noqa: E501

    id: StrictStr
    name: StrictStr
    callback_urls: List[StrictStr] | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    owner: ApiApplicationResponseOwner | None = None
    preferences: ApiApplicationResponsePreferences | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "callback_urls",
        "created_at",
        "updated_at",
        "owner",
        "preferences",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ApiApplicationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict["owner"] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of preferences
        if self.preferences:
            _dict["preferences"] = self.preferences.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if callback_urls (nullable) is None
        # and model_fields_set contains the field
        if self.callback_urls is None and "callback_urls" in self.model_fields_set:
            _dict["callback_urls"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of ApiApplicationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "callback_urls": obj.get("callback_urls"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "owner": ApiApplicationResponseOwner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
                "preferences": ApiApplicationResponsePreferences.from_dict(obj["preferences"])
                if obj.get("preferences") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
