"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Any, Optional, Set
from typing_extensions import Self


class BulkSendValidateCsvResponse(BaseModel):
    """
    Validated bulk send CSV response with defaults applied
    """  # noqa: E501

    bulk_send_csv: StrictStr = Field(description="Base64-encoded CSV content")
    template_ids: List[StrictStr]
    skip_row_errors: StrictBool | None = None
    api_application_id: StrictStr | None = None
    name: StrictStr | None = None
    subject: StrictStr | None = None
    message: StrictStr | None = None
    apply_signing_order: StrictBool | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "bulk_send_csv",
        "template_ids",
        "skip_row_errors",
        "api_application_id",
        "name",
        "subject",
        "message",
        "apply_signing_order",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of BulkSendValidateCsvResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_application_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_application_id is None and "api_application_id" in self.model_fields_set:
            _dict["api_application_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of BulkSendValidateCsvResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "bulk_send_csv": obj.get("bulk_send_csv"),
                "template_ids": obj.get("template_ids"),
                "skip_row_errors": obj.get("skip_row_errors"),
                "api_application_id": obj.get("api_application_id"),
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "apply_signing_order": obj.get("apply_signing_order"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
