"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckboxValidation(str, Enum):
    """
    Validation rule for checkbox groups
    """

    """
    allowed enum values
    """
    MINIMUM = "minimum"
    MAXIMUM = "maximum"
    RANGE = "range"
    EXACT = "exact"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckboxValidation from a JSON string"""
        return cls(json.loads(json_str))
