"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.checkbox_validation import CheckboxValidation
from typing import Any, Optional, Set
from typing_extensions import Self


class CheckboxGroupsInner(BaseModel):
    """
    CheckboxGroupsInner
    """  # noqa: E501

    group_name: StrictStr = Field(description="A unique identifier for the checkbox group.")
    recipient_id: StrictStr = Field(description="The recipient ID associated with the checkbox group.")
    checkbox_ids: List[StrictStr]
    validation: CheckboxValidation | None = None
    required: StrictBool | None = Field(
        default=False, description="Whether the group must be completed by the recipient. Defaults to false."
    )
    min_value: StrictInt | None = Field(
        default=None,
        description="The minimum number of checkboxes that must be checked in the group. (Only for validation: minimum and range)",
    )
    max_value: StrictInt | None = Field(
        default=None,
        description="The maximum number of checkboxes that can be checked in the group. (Only for validation: maximum and range)",
    )
    exact_value: StrictInt | None = Field(
        default=None,
        description="The exact number of checkboxes that must be checked in the group. (Only for validation: exact)",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "group_name",
        "recipient_id",
        "checkbox_ids",
        "validation",
        "required",
        "min_value",
        "max_value",
        "exact_value",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CheckboxGroupsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of CheckboxGroupsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "group_name": obj.get("group_name"),
                "recipient_id": obj.get("recipient_id"),
                "checkbox_ids": obj.get("checkbox_ids"),
                "validation": obj.get("validation"),
                "required": obj.get("required") if obj.get("required") is not None else False,
                "min_value": obj.get("min_value"),
                "max_value": obj.get("max_value"),
                "exact_value": obj.get("exact_value"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
