"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.checkbox_validation import CheckboxValidation
from typing import Any, Optional, Set
from typing_extensions import Self


class CheckboxGroupInfo(BaseModel):
    """
    Checkbox group configuration
    """  # noqa: E501

    id: StrictStr = Field(description="Checkbox group ID")
    group_name: StrictStr | None = Field(default=None, description="Name of the checkbox group")
    recipient_id: StrictStr | None = Field(default=None, description="Recipient ID associated with the group")
    checkbox_ids: List[StrictStr] = Field(description="IDs of checkboxes in this group")
    validation: CheckboxValidation | None = None
    required: StrictBool = Field(description="Whether at least one checkbox must be checked")
    min_value: StrictInt | None = Field(default=None, description="Minimum number of checkboxes to check")
    max_value: StrictInt | None = Field(default=None, description="Maximum number of checkboxes to check")
    exact_value: StrictInt | None = Field(default=None, description="Exact number of checkboxes that must be checked")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "group_name",
        "recipient_id",
        "checkbox_ids",
        "validation",
        "required",
        "min_value",
        "max_value",
        "exact_value",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CheckboxGroupInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if group_name (nullable) is None
        # and model_fields_set contains the field
        if self.group_name is None and "group_name" in self.model_fields_set:
            _dict["group_name"] = None

        # set to None if recipient_id (nullable) is None
        # and model_fields_set contains the field
        if self.recipient_id is None and "recipient_id" in self.model_fields_set:
            _dict["recipient_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of CheckboxGroupInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "group_name": obj.get("group_name"),
                "recipient_id": obj.get("recipient_id"),
                "checkbox_ids": obj.get("checkbox_ids"),
                "validation": obj.get("validation"),
                "required": obj.get("required"),
                "min_value": obj.get("min_value"),
                "max_value": obj.get("max_value"),
                "exact_value": obj.get("exact_value"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
