"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Any, Optional, Set
from typing_extensions import Self


class CreateBulkSendRequest(BaseModel):
    """
    CreateBulkSendRequest
    """  # noqa: E501

    template_ids: List[StrictStr] = Field(description="Unique identifiers for a list of templates.")
    bulk_send_csv: StrictStr = Field(description="A RFC 4648 base64 string of the template CSV file to be validated.")
    skip_row_errors: StrictBool | None = Field(
        default=False, description="Whether to skip errors in the rows. Defaults to `false`."
    )
    api_application_id: StrictStr | None = Field(
        default=None,
        description="Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings",
    )
    name: StrictStr | None = Field(
        default=None,
        description="The name of the Bulk Send. Will be used as the document name for each of the documents.",
    )
    subject: StrictStr | None = Field(
        default=None,
        description="Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject.",
    )
    message: StrictStr | None = Field(
        default=None,
        description="Email message for the signature request that recipients will see. Defaults to the default system message or a template message.",
    )
    apply_signing_order: StrictBool | None = Field(
        default=False,
        description="When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.",
    )
    custom_requester_name: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.",
    )
    custom_requester_email: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "template_ids",
        "bulk_send_csv",
        "skip_row_errors",
        "api_application_id",
        "name",
        "subject",
        "message",
        "apply_signing_order",
        "custom_requester_name",
        "custom_requester_email",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CreateBulkSendRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of CreateBulkSendRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "template_ids": obj.get("template_ids"),
                "bulk_send_csv": obj.get("bulk_send_csv"),
                "skip_row_errors": obj.get("skip_row_errors") if obj.get("skip_row_errors") is not None else False,
                "api_application_id": obj.get("api_application_id"),
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "apply_signing_order": obj.get("apply_signing_order")
                if obj.get("apply_signing_order") is not None
                else False,
                "custom_requester_name": obj.get("custom_requester_name"),
                "custom_requester_email": obj.get("custom_requester_email"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
