"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DateFormat(str, Enum):
    """
    Date format for date fields. Valid values: MM/DD/YYYY, DD/MM/YYYY, YYYY/MM/DD, Month DD, YYYY, MM/DD/YYYY hh:mm:ss a. Default: MM/DD/YYYY
    """

    """
    allowed enum values
    """
    MM_SLASH_DD_SLASH_YYYY = "MM/DD/YYYY"
    DD_SLASH_MM_SLASH_YYYY = "DD/MM/YYYY"
    YYYY_SLASH_MM_SLASH_DD = "YYYY/MM/DD"
    MONTH_DD_COMMA__YYYY = "Month DD, YYYY"
    MM_SLASH_DD_SLASH_YYYY_HH_COLON_MM_COLON_SS_A = "MM/DD/YYYY hh:mm:ss a"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DateFormat from a JSON string"""
        return cls(json.loads(json_str))
