"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.checkbox_group_info import CheckboxGroupInfo
from signwell_sdk.models.copied_contact_info import CopiedContactInfo
from signwell_sdk.models.document_from_template_response_fields_inner_inner import (
    DocumentFromTemplateResponseFieldsInnerInner,
)
from signwell_sdk.models.document_from_template_response_recipients_inner import (
    DocumentFromTemplateResponseRecipientsInner,
)
from signwell_sdk.models.document_response_attachment_requests_inner import DocumentResponseAttachmentRequestsInner
from signwell_sdk.models.file_info import FileInfo
from signwell_sdk.models.label_info import LabelInfo
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentFromTemplateResponse(BaseModel):
    """
    DocumentFromTemplateResponse
    """  # noqa: E501

    test_mode: StrictBool
    id: StrictStr
    template_id: StrictStr | None = None
    template_ids: List[StrictStr] | None = None
    api_application_id: StrictStr | None = None
    requester_email_address: StrictStr | None = None
    custom_requester_name: StrictStr | None = None
    custom_requester_email: StrictStr | None = None
    name: StrictStr | None = None
    subject: StrictStr | None = None
    message: StrictStr | None = None
    metadata: Dict[str, StrictStr] | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    recipients: List[DocumentFromTemplateResponseRecipientsInner] | None = None
    status: StrictStr | None = Field(
        default=None,
        description="Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired",
    )
    reminders: StrictBool | None = None
    archived: StrictBool | None = None
    embedded_signing: StrictBool | None = None
    embedded_edit_url: StrictStr | None = None
    embedded_preview_url: StrictStr | None = None
    apply_signing_order: StrictBool | None = None
    redirect_url: StrictStr | None = None
    decline_redirect_url: StrictStr | None = None
    language: StrictStr | None = None
    expires_in: StrictInt | None = None
    decline_message: StrictStr | None = None
    error_message: StrictStr | None = None
    embedded_signing_notifications: StrictBool | None = None
    attachment_requests: List[DocumentResponseAttachmentRequestsInner] | None = None
    files: List[FileInfo] | None = None
    copied_contacts: List[CopiedContactInfo] | None = None
    fields: List[List[DocumentFromTemplateResponseFieldsInnerInner]] | None = None
    allow_decline: StrictBool | None = None
    allow_reassign: StrictBool | None = None
    labels: List[LabelInfo] | None = None
    checkbox_groups: List[CheckboxGroupInfo] | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "test_mode",
        "id",
        "template_id",
        "template_ids",
        "api_application_id",
        "requester_email_address",
        "custom_requester_name",
        "custom_requester_email",
        "name",
        "subject",
        "message",
        "metadata",
        "created_at",
        "updated_at",
        "recipients",
        "status",
        "reminders",
        "archived",
        "embedded_signing",
        "embedded_edit_url",
        "embedded_preview_url",
        "apply_signing_order",
        "redirect_url",
        "decline_redirect_url",
        "language",
        "expires_in",
        "decline_message",
        "error_message",
        "embedded_signing_notifications",
        "attachment_requests",
        "files",
        "copied_contacts",
        "fields",
        "allow_decline",
        "allow_reassign",
        "labels",
        "checkbox_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentFromTemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items_recipients: list[Any] = []
        if self.recipients:
            for _item_recipients in self.recipients:
                if _item_recipients:
                    _items_recipients.append(_item_recipients.to_dict())
            _dict["recipients"] = _items_recipients
        # override the default output from pydantic by calling `to_dict()` of each item in attachment_requests (list)
        _items_attachment_requests: list[Any] = []
        if self.attachment_requests:
            for _item_attachment_requests in self.attachment_requests:
                if _item_attachment_requests:
                    _items_attachment_requests.append(_item_attachment_requests.to_dict())
            _dict["attachment_requests"] = _items_attachment_requests
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items_files: list[Any] = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items_files.append(_item_files.to_dict())
            _dict["files"] = _items_files
        # override the default output from pydantic by calling `to_dict()` of each item in copied_contacts (list)
        _items_copied_contacts: list[Any] = []
        if self.copied_contacts:
            for _item_copied_contacts in self.copied_contacts:
                if _item_copied_contacts:
                    _items_copied_contacts.append(_item_copied_contacts.to_dict())
            _dict["copied_contacts"] = _items_copied_contacts
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list of list)
        _items_fields: list[Any] = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items_fields.append(
                        [_inner_item.to_dict() for _inner_item in _item_fields if _inner_item is not None]
                    )
            _dict["fields"] = _items_fields
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items_labels: list[Any] = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items_labels.append(_item_labels.to_dict())
            _dict["labels"] = _items_labels
        # override the default output from pydantic by calling `to_dict()` of each item in checkbox_groups (list)
        _items_checkbox_groups: list[Any] = []
        if self.checkbox_groups:
            for _item_checkbox_groups in self.checkbox_groups:
                if _item_checkbox_groups:
                    _items_checkbox_groups.append(_item_checkbox_groups.to_dict())
            _dict["checkbox_groups"] = _items_checkbox_groups
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_application_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_application_id is None and "api_application_id" in self.model_fields_set:
            _dict["api_application_id"] = None

        # set to None if custom_requester_name (nullable) is None
        # and model_fields_set contains the field
        if self.custom_requester_name is None and "custom_requester_name" in self.model_fields_set:
            _dict["custom_requester_name"] = None

        # set to None if custom_requester_email (nullable) is None
        # and model_fields_set contains the field
        if self.custom_requester_email is None and "custom_requester_email" in self.model_fields_set:
            _dict["custom_requester_email"] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict["metadata"] = None

        # set to None if embedded_preview_url (nullable) is None
        # and model_fields_set contains the field
        if self.embedded_preview_url is None and "embedded_preview_url" in self.model_fields_set:
            _dict["embedded_preview_url"] = None

        # set to None if redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_url is None and "redirect_url" in self.model_fields_set:
            _dict["redirect_url"] = None

        # set to None if decline_redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.decline_redirect_url is None and "decline_redirect_url" in self.model_fields_set:
            _dict["decline_redirect_url"] = None

        # set to None if decline_message (nullable) is None
        # and model_fields_set contains the field
        if self.decline_message is None and "decline_message" in self.model_fields_set:
            _dict["decline_message"] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict["error_message"] = None

        # set to None if allow_decline (nullable) is None
        # and model_fields_set contains the field
        if self.allow_decline is None and "allow_decline" in self.model_fields_set:
            _dict["allow_decline"] = None

        # set to None if allow_reassign (nullable) is None
        # and model_fields_set contains the field
        if self.allow_reassign is None and "allow_reassign" in self.model_fields_set:
            _dict["allow_reassign"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentFromTemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "test_mode": obj.get("test_mode"),
                "id": obj.get("id"),
                "template_id": obj.get("template_id"),
                "template_ids": obj.get("template_ids"),
                "api_application_id": obj.get("api_application_id"),
                "requester_email_address": obj.get("requester_email_address"),
                "custom_requester_name": obj.get("custom_requester_name"),
                "custom_requester_email": obj.get("custom_requester_email"),
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "metadata": obj.get("metadata"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "recipients": [
                    DocumentFromTemplateResponseRecipientsInner.from_dict(_item) for _item in obj["recipients"]
                ]
                if obj.get("recipients") is not None
                else None,
                "status": obj.get("status"),
                "reminders": obj.get("reminders"),
                "archived": obj.get("archived"),
                "embedded_signing": obj.get("embedded_signing"),
                "embedded_edit_url": obj.get("embedded_edit_url"),
                "embedded_preview_url": obj.get("embedded_preview_url"),
                "apply_signing_order": obj.get("apply_signing_order"),
                "redirect_url": obj.get("redirect_url"),
                "decline_redirect_url": obj.get("decline_redirect_url"),
                "language": obj.get("language"),
                "expires_in": obj.get("expires_in"),
                "decline_message": obj.get("decline_message"),
                "error_message": obj.get("error_message"),
                "embedded_signing_notifications": obj.get("embedded_signing_notifications"),
                "attachment_requests": [
                    DocumentResponseAttachmentRequestsInner.from_dict(_item) for _item in obj["attachment_requests"]
                ]
                if obj.get("attachment_requests") is not None
                else None,
                "files": [FileInfo.from_dict(_item) for _item in obj["files"]]
                if obj.get("files") is not None
                else None,
                "copied_contacts": [CopiedContactInfo.from_dict(_item) for _item in obj["copied_contacts"]]
                if obj.get("copied_contacts") is not None
                else None,
                "fields": [
                    [DocumentFromTemplateResponseFieldsInnerInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["fields"]
                ]
                if obj.get("fields") is not None
                else None,
                "allow_decline": obj.get("allow_decline"),
                "allow_reassign": obj.get("allow_reassign"),
                "labels": [LabelInfo.from_dict(_item) for _item in obj["labels"]]
                if obj.get("labels") is not None
                else None,
                "checkbox_groups": [CheckboxGroupInfo.from_dict(_item) for _item in obj["checkbox_groups"]]
                if obj.get("checkbox_groups") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
