"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signwell_sdk.models.additional_fields_inner_inner import AdditionalFieldsInnerInner
from signwell_sdk.models.additional_files_inner import AdditionalFilesInner
from signwell_sdk.models.attachment_requests_inner import AttachmentRequestsInner
from signwell_sdk.models.checkbox_groups_inner import CheckboxGroupsInner
from signwell_sdk.models.copied_contacts_inner import CopiedContactsInner
from signwell_sdk.models.label_request import LabelRequest
from signwell_sdk.models.template_field_values_inner import TemplateFieldValuesInner
from signwell_sdk.models.template_recipients_inner import TemplateRecipientsInner
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentFromTemplateRequest(BaseModel):
    """
    DocumentFromTemplateRequest
    """  # noqa: E501

    test_mode: StrictBool | None = Field(
        default=False,
        description="Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`",
    )
    template_id: StrictStr | None = Field(
        default=None,
        description="Use when you have to create a document from a single template. Either :template_id or :template_ids must be present in the request, not both.",
    )
    template_ids: List[StrictStr] | None = Field(
        default=None,
        description="Use when you have to create a document from multiple templates. Either :template_id or :template_ids must be present in the request, not both.",
    )
    name: StrictStr | None = Field(default=None, description="The name of the document.")
    subject: StrictStr | None = Field(
        default=None,
        description="Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).",
    )
    message: StrictStr | None = Field(
        default=None,
        description="Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).",
    )
    recipients: List[TemplateRecipientsInner] = Field(
        description="Document recipients are people that must complete and/or sign a document. Recipients of the document must be assigned to a placeholder of the template. Recipients will inherit all placeholder fields and settings."
    )
    exclude_placeholders: List[StrictStr] | None = Field(
        default=None,
        description="Exclude one or more template placeholders when creating a document from a template. Any excluded placeholders (and their associated recipients and fields) will not be included on the created document. Values must match placeholder names on the template. You can't exclude all placeholders (at least one recipient must remain).",
    )
    draft: StrictBool | None = Field(
        default=False,
        description="Whether the document can still be updated before sending a signature request. If set to `false` the document is sent for signing as part of this request. Defaults to `false`.",
    )
    with_signature_page: StrictBool | None = Field(
        default=False,
        description="When set to `true` the document will have a signature page added to the end, and all signers will be required to add their signature on that page.",
    )
    expires_in: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None,
        description="Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).",
    )
    reminders: StrictBool | None = Field(
        default=True,
        description="Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.",
    )
    apply_signing_order: StrictBool | None = Field(
        default=False,
        description="When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.",
    )
    api_application_id: StrictStr | None = Field(
        default=None,
        description="Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings",
    )
    embedded_signing: StrictBool | None = Field(
        default=False,
        description="When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.",
    )
    embedded_signing_notifications: StrictBool | None = Field(
        default=False,
        description="On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`",
    )
    text_tags: StrictBool | None = Field(
        default=False,
        description="An alternative way (if you can’t use the recommended way) of placing fields in specific locations of your document by using special text tags. Useful when changing the content of your files changes the location of fields. See API documentation for “Text Tags” for details. Defaults to false.",
    )
    custom_requester_name: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.",
    )
    custom_requester_email: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.",
    )
    redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to after successfully signing a document."
    )
    allow_decline: StrictBool | None = Field(
        default=True,
        description="Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.",
    )
    allow_reassign: StrictBool | None = Field(
        default=True,
        description="In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.",
    )
    decline_redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to if the document is declined."
    )
    language: StrictStr | None = Field(
        default=None,
        description="Sets the language for all recipients on the document and updates all recipient side interactions including the document email and the document itself. Accepted languages: English, Français, Español, Deutsch, Polski, Português, Dansk, Nederlands, Italiano, Русский, Svenska, العربية, Ελληνικά, Türkçe, Slovenčina. Defaults to English. Language should be sent in ISO 639-1 format: en, fr, es, de, pl, pt, da, nl, it, ru, sv, ar, el, tr, sk.",
    )
    metadata: Dict[str, StrictStr] | None = Field(
        default=None,
        description="Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.",
    )
    template_fields: List[TemplateFieldValuesInner] | None = Field(
        default=None,
        description="Fields of your template(s) that you can prepopulate with values. Signature and Initials fields cannot be signed through the API.",
    )
    files: List[AdditionalFilesInner] | None = None
    fields: List[List[AdditionalFieldsInnerInner]] | None = Field(
        default=None,
        description="Fields to be added to any appended files (not existing files). Document fields placed on a document for collecting data or signatures from recipients. Field data should be sent as a 2-dimensional JSON array. One array of fields is needed for each file in the files array. An array of fields can be empty if you have a file that does not contain any fields.",
    )
    attachment_requests: List[AttachmentRequestsInner] | None = Field(
        default=None,
        description="Attachments that a recipient must upload to complete the signing process. Attachment requests are shown after all document fields have been completed.",
    )
    copied_contacts: List[CopiedContactsInner] | None = Field(
        default=None,
        description="Copied contacts are emailed the final document once it has been completed by all recipients.",
    )
    labels: List[LabelRequest] | None = Field(
        default=None,
        description="Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.",
    )
    checkbox_groups: List[CheckboxGroupsInner] | None = Field(
        default=None,
        description="Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "test_mode",
        "template_id",
        "template_ids",
        "name",
        "subject",
        "message",
        "recipients",
        "exclude_placeholders",
        "draft",
        "with_signature_page",
        "expires_in",
        "reminders",
        "apply_signing_order",
        "api_application_id",
        "embedded_signing",
        "embedded_signing_notifications",
        "text_tags",
        "custom_requester_name",
        "custom_requester_email",
        "redirect_url",
        "allow_decline",
        "allow_reassign",
        "decline_redirect_url",
        "language",
        "metadata",
        "template_fields",
        "files",
        "fields",
        "attachment_requests",
        "copied_contacts",
        "labels",
        "checkbox_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentFromTemplateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items_recipients: list[Any] = []
        if self.recipients:
            for _item_recipients in self.recipients:
                if _item_recipients:
                    _items_recipients.append(_item_recipients.to_dict())
            _dict["recipients"] = _items_recipients
        # override the default output from pydantic by calling `to_dict()` of each item in template_fields (list)
        _items_template_fields: list[Any] = []
        if self.template_fields:
            for _item_template_fields in self.template_fields:
                if _item_template_fields:
                    _items_template_fields.append(_item_template_fields.to_dict())
            _dict["template_fields"] = _items_template_fields
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items_files: list[Any] = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items_files.append(_item_files.to_dict())
            _dict["files"] = _items_files
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list of list)
        _items_fields: list[Any] = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items_fields.append(
                        [_inner_item.to_dict() for _inner_item in _item_fields if _inner_item is not None]
                    )
            _dict["fields"] = _items_fields
        # override the default output from pydantic by calling `to_dict()` of each item in attachment_requests (list)
        _items_attachment_requests: list[Any] = []
        if self.attachment_requests:
            for _item_attachment_requests in self.attachment_requests:
                if _item_attachment_requests:
                    _items_attachment_requests.append(_item_attachment_requests.to_dict())
            _dict["attachment_requests"] = _items_attachment_requests
        # override the default output from pydantic by calling `to_dict()` of each item in copied_contacts (list)
        _items_copied_contacts: list[Any] = []
        if self.copied_contacts:
            for _item_copied_contacts in self.copied_contacts:
                if _item_copied_contacts:
                    _items_copied_contacts.append(_item_copied_contacts.to_dict())
            _dict["copied_contacts"] = _items_copied_contacts
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items_labels: list[Any] = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items_labels.append(_item_labels.to_dict())
            _dict["labels"] = _items_labels
        # override the default output from pydantic by calling `to_dict()` of each item in checkbox_groups (list)
        _items_checkbox_groups: list[Any] = []
        if self.checkbox_groups:
            for _item_checkbox_groups in self.checkbox_groups:
                if _item_checkbox_groups:
                    _items_checkbox_groups.append(_item_checkbox_groups.to_dict())
            _dict["checkbox_groups"] = _items_checkbox_groups
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentFromTemplateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "test_mode": obj.get("test_mode") if obj.get("test_mode") is not None else False,
                "template_id": obj.get("template_id"),
                "template_ids": obj.get("template_ids"),
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "recipients": [TemplateRecipientsInner.from_dict(_item) for _item in obj["recipients"]]
                if obj.get("recipients") is not None
                else None,
                "exclude_placeholders": obj.get("exclude_placeholders"),
                "draft": obj.get("draft") if obj.get("draft") is not None else False,
                "with_signature_page": obj.get("with_signature_page")
                if obj.get("with_signature_page") is not None
                else False,
                "expires_in": obj.get("expires_in"),
                "reminders": obj.get("reminders") if obj.get("reminders") is not None else True,
                "apply_signing_order": obj.get("apply_signing_order")
                if obj.get("apply_signing_order") is not None
                else False,
                "api_application_id": obj.get("api_application_id"),
                "embedded_signing": obj.get("embedded_signing") if obj.get("embedded_signing") is not None else False,
                "embedded_signing_notifications": obj.get("embedded_signing_notifications")
                if obj.get("embedded_signing_notifications") is not None
                else False,
                "text_tags": obj.get("text_tags") if obj.get("text_tags") is not None else False,
                "custom_requester_name": obj.get("custom_requester_name"),
                "custom_requester_email": obj.get("custom_requester_email"),
                "redirect_url": obj.get("redirect_url"),
                "allow_decline": obj.get("allow_decline") if obj.get("allow_decline") is not None else True,
                "allow_reassign": obj.get("allow_reassign") if obj.get("allow_reassign") is not None else True,
                "decline_redirect_url": obj.get("decline_redirect_url"),
                "language": obj.get("language"),
                "metadata": obj.get("metadata"),
                "template_fields": [TemplateFieldValuesInner.from_dict(_item) for _item in obj["template_fields"]]
                if obj.get("template_fields") is not None
                else None,
                "files": [AdditionalFilesInner.from_dict(_item) for _item in obj["files"]]
                if obj.get("files") is not None
                else None,
                "fields": [
                    [AdditionalFieldsInnerInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["fields"]
                ]
                if obj.get("fields") is not None
                else None,
                "attachment_requests": [
                    AttachmentRequestsInner.from_dict(_item) for _item in obj["attachment_requests"]
                ]
                if obj.get("attachment_requests") is not None
                else None,
                "copied_contacts": [CopiedContactsInner.from_dict(_item) for _item in obj["copied_contacts"]]
                if obj.get("copied_contacts") is not None
                else None,
                "labels": [LabelRequest.from_dict(_item) for _item in obj["labels"]]
                if obj.get("labels") is not None
                else None,
                "checkbox_groups": [CheckboxGroupsInner.from_dict(_item) for _item in obj["checkbox_groups"]]
                if obj.get("checkbox_groups") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
