"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from signwell_sdk.models.date_format import DateFormat
from signwell_sdk.models.document_from_template_response_fields_inner_inner_recipient import (
    DocumentFromTemplateResponseFieldsInnerInnerRecipient,
)
from signwell_sdk.models.document_response_fields_inner_inner_options_inner import (
    DocumentResponseFieldsInnerInnerOptionsInner,
)
from signwell_sdk.models.document_response_fields_inner_inner_value import DocumentResponseFieldsInnerInnerValue
from signwell_sdk.models.field_type import FieldType
from signwell_sdk.models.text_validation import TextValidation
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentFromTemplateResponseFieldsInnerInner(BaseModel):
    """
    DocumentFromTemplateResponseFieldsInnerInner
    """  # noqa: E501

    x: Union[StrictFloat, StrictInt]
    y: Union[StrictFloat, StrictInt]
    page: StrictInt
    recipient: DocumentFromTemplateResponseFieldsInnerInnerRecipient | None = None
    api_id: StrictStr | None = None
    name: StrictStr | None = None
    date_format: DateFormat | None = None
    fixed_width: StrictBool | None = None
    formula: StrictStr | None = None
    label: StrictStr | None = None
    lock_sign_date: StrictBool | None = None
    required: StrictBool | None = None
    type: FieldType | None = None
    validation: TextValidation | None = None
    value: DocumentResponseFieldsInnerInnerValue | None = None
    height: StrictStr | None = None
    width: StrictStr | None = None
    recipient_id: StrictStr | None = None
    signing_elements_group_id: StrictStr | None = None
    placeholder_name: StrictStr | None = None
    options: List[DocumentResponseFieldsInnerInnerOptionsInner] | None = Field(
        default=None, description="Dropdown options (for dropdown/select fields)"
    )
    default_option: StrictStr | None = Field(default=None, description="Default selected option")
    allow_other: StrictBool | None = Field(default=None, description='Whether "Other" option is allowed')
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "x",
        "y",
        "page",
        "recipient",
        "api_id",
        "name",
        "date_format",
        "fixed_width",
        "formula",
        "label",
        "lock_sign_date",
        "required",
        "type",
        "validation",
        "value",
        "height",
        "width",
        "recipient_id",
        "signing_elements_group_id",
        "placeholder_name",
        "options",
        "default_option",
        "allow_other",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentFromTemplateResponseFieldsInnerInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict["recipient"] = self.recipient.to_dict()
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict["value"] = self.value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items_options: list[Any] = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items_options.append(_item_options.to_dict())
            _dict["options"] = _items_options
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict["value"] = None

        # set to None if recipient_id (nullable) is None
        # and model_fields_set contains the field
        if self.recipient_id is None and "recipient_id" in self.model_fields_set:
            _dict["recipient_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentFromTemplateResponseFieldsInnerInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "x": obj.get("x"),
                "y": obj.get("y"),
                "page": obj.get("page"),
                "recipient": DocumentFromTemplateResponseFieldsInnerInnerRecipient.from_dict(obj["recipient"])
                if obj.get("recipient") is not None
                else None,
                "api_id": obj.get("api_id"),
                "name": obj.get("name"),
                "date_format": obj.get("date_format"),
                "fixed_width": obj.get("fixed_width"),
                "formula": obj.get("formula"),
                "label": obj.get("label"),
                "lock_sign_date": obj.get("lock_sign_date"),
                "required": obj.get("required"),
                "type": obj.get("type"),
                "validation": obj.get("validation"),
                "value": DocumentResponseFieldsInnerInnerValue.from_dict(obj["value"])
                if obj.get("value") is not None
                else None,
                "height": obj.get("height"),
                "width": obj.get("width"),
                "recipient_id": obj.get("recipient_id"),
                "signing_elements_group_id": obj.get("signing_elements_group_id"),
                "placeholder_name": obj.get("placeholder_name"),
                "options": [DocumentResponseFieldsInnerInnerOptionsInner.from_dict(_item) for _item in obj["options"]]
                if obj.get("options") is not None
                else None,
                "default_option": obj.get("default_option"),
                "allow_other": obj.get("allow_other"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
