"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signwell_sdk.models.copied_placeholders_inner import CopiedPlaceholdersInner
from signwell_sdk.models.files_inner import FilesInner
from signwell_sdk.models.label_request import LabelRequest
from signwell_sdk.models.placeholders_inner import PlaceholdersInner
from signwell_sdk.models.template_attachment_requests_inner import TemplateAttachmentRequestsInner
from signwell_sdk.models.template_checkbox_groups_inner import TemplateCheckboxGroupsInner
from signwell_sdk.models.template_fields_inner_inner import TemplateFieldsInnerInner
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentTemplateRequest(BaseModel):
    """
    DocumentTemplateRequest
    """  # noqa: E501

    files: List[FilesInner] = Field(
        description="Document files can be uploaded by specifying a file URL or base64 string. Either `file_url` or `file_base64` must be present (not both). Valid file types are: .pdf, .doc, .docx, .pages, .ppt, .pptx, .key, .xls, .xlsx, .numbers, .jpg, .jpeg, .png, .tiff, .tif, .webp, .html, and .htm"
    )
    name: StrictStr | None = Field(default=None, description="The name of the template.")
    subject: StrictStr | None = Field(
        default=None,
        description="Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).",
    )
    message: StrictStr | None = Field(
        default=None,
        description="Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).",
    )
    placeholders: List[PlaceholdersInner] = Field(
        description="Placeholders are generally job roles that must complete and/or sign the document. For example, a placeholder might be “Client” or “Legal Department”. When a document is created from the template, you assign a person to each placeholder."
    )
    copied_placeholders: List[CopiedPlaceholdersInner] | None = Field(
        default=None,
        description="Copied placeholders are emailed the final document once it has been completed by all recipients.",
    )
    draft: StrictBool | None = Field(
        default=False,
        description="Whether the template can still be updated before it is ready for usage. If set to `false` the template is marked as `Available` and it will be ready for use. Defaults to `false`.",
    )
    expires_in: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None,
        description="Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).",
    )
    reminders: StrictBool | None = Field(
        default=True,
        description="Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.",
    )
    apply_signing_order: StrictBool | None = Field(
        default=False,
        description="When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.",
    )
    api_application_id: StrictStr | None = Field(
        default=None,
        description="Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings",
    )
    text_tags: StrictBool | None = Field(
        default=False,
        description="An alternative way (if you can’t use the recommended way) of placing fields in specific locations of your document by using special text tags. Useful when changing the content of your files changes the location of fields. See API documentation for “Text Tags” for details. Defaults to false.",
    )
    redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to after successfully signing a document."
    )
    allow_decline: StrictBool | None = Field(
        default=True,
        description="Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.",
    )
    allow_reassign: StrictBool | None = Field(
        default=True,
        description="In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.",
    )
    decline_redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to if the document is declined."
    )
    language: StrictStr | None = Field(
        default=None,
        description="Sets the language for the template and documents created from the template for all recipient side interactions including the document email and the document itself. Accepted languages: English, Français, Español, Deutsch, Polski, Português, Dansk, Nederlands, Italiano, Русский, Svenska, العربية, Ελληνικά, Türkçe, Slovenčina. Language should be sent in ISO 639-1 format: en, fr, es, de, pl, pt, da, nl, it, ru, sv, ar, el, tr, sk.",
    )
    metadata: Dict[str, StrictStr] | None = Field(
        default=None,
        description="Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.",
    )
    fields: List[List[TemplateFieldsInnerInner]] | None = Field(
        default=None,
        description="Document fields placed on a document for collecting data or signatures from recipients. At least one field must be present in the Create Document request if `draft` is `false` (unless adding a signature page by using `with_signature_page`). Field data should be sent as a 2-dimensional JSON array. One array of fields is needed for each file in the files array. An array of fields can be empty if you have a file that does not contain any fields.",
    )
    attachment_requests: List[TemplateAttachmentRequestsInner] | None = Field(
        default=None,
        description="Attachments that a recipient must upload to complete the signing process. Attachment requests are shown after all document fields have been completed.",
    )
    labels: List[LabelRequest] | None = Field(
        default=None,
        description="Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels.",
    )
    checkbox_groups: List[TemplateCheckboxGroupsInner] | None = Field(
        default=None,
        description="Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "files",
        "name",
        "subject",
        "message",
        "placeholders",
        "copied_placeholders",
        "draft",
        "expires_in",
        "reminders",
        "apply_signing_order",
        "api_application_id",
        "text_tags",
        "redirect_url",
        "allow_decline",
        "allow_reassign",
        "decline_redirect_url",
        "language",
        "metadata",
        "fields",
        "attachment_requests",
        "labels",
        "checkbox_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentTemplateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items_files: list[Any] = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items_files.append(_item_files.to_dict())
            _dict["files"] = _items_files
        # override the default output from pydantic by calling `to_dict()` of each item in placeholders (list)
        _items_placeholders: list[Any] = []
        if self.placeholders:
            for _item_placeholders in self.placeholders:
                if _item_placeholders:
                    _items_placeholders.append(_item_placeholders.to_dict())
            _dict["placeholders"] = _items_placeholders
        # override the default output from pydantic by calling `to_dict()` of each item in copied_placeholders (list)
        _items_copied_placeholders: list[Any] = []
        if self.copied_placeholders:
            for _item_copied_placeholders in self.copied_placeholders:
                if _item_copied_placeholders:
                    _items_copied_placeholders.append(_item_copied_placeholders.to_dict())
            _dict["copied_placeholders"] = _items_copied_placeholders
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list of list)
        _items_fields: list[Any] = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items_fields.append(
                        [_inner_item.to_dict() for _inner_item in _item_fields if _inner_item is not None]
                    )
            _dict["fields"] = _items_fields
        # override the default output from pydantic by calling `to_dict()` of each item in attachment_requests (list)
        _items_attachment_requests: list[Any] = []
        if self.attachment_requests:
            for _item_attachment_requests in self.attachment_requests:
                if _item_attachment_requests:
                    _items_attachment_requests.append(_item_attachment_requests.to_dict())
            _dict["attachment_requests"] = _items_attachment_requests
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items_labels: list[Any] = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items_labels.append(_item_labels.to_dict())
            _dict["labels"] = _items_labels
        # override the default output from pydantic by calling `to_dict()` of each item in checkbox_groups (list)
        _items_checkbox_groups: list[Any] = []
        if self.checkbox_groups:
            for _item_checkbox_groups in self.checkbox_groups:
                if _item_checkbox_groups:
                    _items_checkbox_groups.append(_item_checkbox_groups.to_dict())
            _dict["checkbox_groups"] = _items_checkbox_groups
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentTemplateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "files": [FilesInner.from_dict(_item) for _item in obj["files"]]
                if obj.get("files") is not None
                else None,
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "placeholders": [PlaceholdersInner.from_dict(_item) for _item in obj["placeholders"]]
                if obj.get("placeholders") is not None
                else None,
                "copied_placeholders": [
                    CopiedPlaceholdersInner.from_dict(_item) for _item in obj["copied_placeholders"]
                ]
                if obj.get("copied_placeholders") is not None
                else None,
                "draft": obj.get("draft") if obj.get("draft") is not None else False,
                "expires_in": obj.get("expires_in"),
                "reminders": obj.get("reminders") if obj.get("reminders") is not None else True,
                "apply_signing_order": obj.get("apply_signing_order")
                if obj.get("apply_signing_order") is not None
                else False,
                "api_application_id": obj.get("api_application_id"),
                "text_tags": obj.get("text_tags") if obj.get("text_tags") is not None else False,
                "redirect_url": obj.get("redirect_url"),
                "allow_decline": obj.get("allow_decline") if obj.get("allow_decline") is not None else True,
                "allow_reassign": obj.get("allow_reassign") if obj.get("allow_reassign") is not None else True,
                "decline_redirect_url": obj.get("decline_redirect_url"),
                "language": obj.get("language"),
                "metadata": obj.get("metadata"),
                "fields": [
                    [TemplateFieldsInnerInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["fields"]
                ]
                if obj.get("fields") is not None
                else None,
                "attachment_requests": [
                    TemplateAttachmentRequestsInner.from_dict(_item) for _item in obj["attachment_requests"]
                ]
                if obj.get("attachment_requests") is not None
                else None,
                "labels": [LabelRequest.from_dict(_item) for _item in obj["labels"]]
                if obj.get("labels") is not None
                else None,
                "checkbox_groups": [TemplateCheckboxGroupsInner.from_dict(_item) for _item in obj["checkbox_groups"]]
                if obj.get("checkbox_groups") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
