"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.checkbox_group_info import CheckboxGroupInfo
from signwell_sdk.models.document_response_fields_inner_inner import DocumentResponseFieldsInnerInner
from signwell_sdk.models.document_template_response_copied_placeholders_inner import (
    DocumentTemplateResponseCopiedPlaceholdersInner,
)
from signwell_sdk.models.document_template_response_placeholders_inner import DocumentTemplateResponsePlaceholdersInner
from signwell_sdk.models.file_info import FileInfo
from signwell_sdk.models.label_info import LabelInfo
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentTemplateResponse(BaseModel):
    """
    DocumentTemplateResponse
    """  # noqa: E501

    id: StrictStr
    api_application_id: StrictStr | None = None
    requester_email_address: StrictStr | None = None
    custom_requester_name: StrictStr | None = None
    custom_requester_email: StrictStr | None = None
    name: StrictStr | None = None
    subject: StrictStr | None = None
    message: StrictStr | None = None
    metadata: Dict[str, StrictStr] | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    placeholders: List[DocumentTemplateResponsePlaceholdersInner] | None = None
    copied_placeholders: List[DocumentTemplateResponseCopiedPlaceholdersInner] | None = None
    status: StrictStr | None = None
    reminders: StrictBool | None = None
    archived: StrictBool | None = None
    embedded_edit_url: StrictStr | None = None
    template_link: StrictStr | None = None
    template_id: StrictStr | None = None
    apply_signing_order: StrictBool | None = None
    redirect_url: StrictStr | None = None
    decline_redirect_url: StrictStr | None = None
    language: StrictStr | None = None
    expires_in: StrictInt | None = None
    files: List[FileInfo] | None = None
    fields: List[List[DocumentResponseFieldsInnerInner]] | None = None
    allow_decline: StrictBool | None = None
    allow_reassign: StrictBool | None = None
    labels: List[LabelInfo] | None = None
    checkbox_groups: List[CheckboxGroupInfo] | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "api_application_id",
        "requester_email_address",
        "custom_requester_name",
        "custom_requester_email",
        "name",
        "subject",
        "message",
        "metadata",
        "created_at",
        "updated_at",
        "placeholders",
        "copied_placeholders",
        "status",
        "reminders",
        "archived",
        "embedded_edit_url",
        "template_link",
        "template_id",
        "apply_signing_order",
        "redirect_url",
        "decline_redirect_url",
        "language",
        "expires_in",
        "files",
        "fields",
        "allow_decline",
        "allow_reassign",
        "labels",
        "checkbox_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentTemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in placeholders (list)
        _items_placeholders: list[Any] = []
        if self.placeholders:
            for _item_placeholders in self.placeholders:
                if _item_placeholders:
                    _items_placeholders.append(_item_placeholders.to_dict())
            _dict["placeholders"] = _items_placeholders
        # override the default output from pydantic by calling `to_dict()` of each item in copied_placeholders (list)
        _items_copied_placeholders: list[Any] = []
        if self.copied_placeholders:
            for _item_copied_placeholders in self.copied_placeholders:
                if _item_copied_placeholders:
                    _items_copied_placeholders.append(_item_copied_placeholders.to_dict())
            _dict["copied_placeholders"] = _items_copied_placeholders
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items_files: list[Any] = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items_files.append(_item_files.to_dict())
            _dict["files"] = _items_files
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list of list)
        _items_fields: list[Any] = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items_fields.append(
                        [_inner_item.to_dict() for _inner_item in _item_fields if _inner_item is not None]
                    )
            _dict["fields"] = _items_fields
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items_labels: list[Any] = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items_labels.append(_item_labels.to_dict())
            _dict["labels"] = _items_labels
        # override the default output from pydantic by calling `to_dict()` of each item in checkbox_groups (list)
        _items_checkbox_groups: list[Any] = []
        if self.checkbox_groups:
            for _item_checkbox_groups in self.checkbox_groups:
                if _item_checkbox_groups:
                    _items_checkbox_groups.append(_item_checkbox_groups.to_dict())
            _dict["checkbox_groups"] = _items_checkbox_groups
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_application_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_application_id is None and "api_application_id" in self.model_fields_set:
            _dict["api_application_id"] = None

        # set to None if custom_requester_name (nullable) is None
        # and model_fields_set contains the field
        if self.custom_requester_name is None and "custom_requester_name" in self.model_fields_set:
            _dict["custom_requester_name"] = None

        # set to None if custom_requester_email (nullable) is None
        # and model_fields_set contains the field
        if self.custom_requester_email is None and "custom_requester_email" in self.model_fields_set:
            _dict["custom_requester_email"] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict["metadata"] = None

        # set to None if reminders (nullable) is None
        # and model_fields_set contains the field
        if self.reminders is None and "reminders" in self.model_fields_set:
            _dict["reminders"] = None

        # set to None if embedded_edit_url (nullable) is None
        # and model_fields_set contains the field
        if self.embedded_edit_url is None and "embedded_edit_url" in self.model_fields_set:
            _dict["embedded_edit_url"] = None

        # set to None if template_id (nullable) is None
        # and model_fields_set contains the field
        if self.template_id is None and "template_id" in self.model_fields_set:
            _dict["template_id"] = None

        # set to None if redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_url is None and "redirect_url" in self.model_fields_set:
            _dict["redirect_url"] = None

        # set to None if decline_redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.decline_redirect_url is None and "decline_redirect_url" in self.model_fields_set:
            _dict["decline_redirect_url"] = None

        # set to None if expires_in (nullable) is None
        # and model_fields_set contains the field
        if self.expires_in is None and "expires_in" in self.model_fields_set:
            _dict["expires_in"] = None

        # set to None if allow_decline (nullable) is None
        # and model_fields_set contains the field
        if self.allow_decline is None and "allow_decline" in self.model_fields_set:
            _dict["allow_decline"] = None

        # set to None if allow_reassign (nullable) is None
        # and model_fields_set contains the field
        if self.allow_reassign is None and "allow_reassign" in self.model_fields_set:
            _dict["allow_reassign"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentTemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "api_application_id": obj.get("api_application_id"),
                "requester_email_address": obj.get("requester_email_address"),
                "custom_requester_name": obj.get("custom_requester_name"),
                "custom_requester_email": obj.get("custom_requester_email"),
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "metadata": obj.get("metadata"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "placeholders": [
                    DocumentTemplateResponsePlaceholdersInner.from_dict(_item) for _item in obj["placeholders"]
                ]
                if obj.get("placeholders") is not None
                else None,
                "copied_placeholders": [
                    DocumentTemplateResponseCopiedPlaceholdersInner.from_dict(_item)
                    for _item in obj["copied_placeholders"]
                ]
                if obj.get("copied_placeholders") is not None
                else None,
                "status": obj.get("status"),
                "reminders": obj.get("reminders"),
                "archived": obj.get("archived"),
                "embedded_edit_url": obj.get("embedded_edit_url"),
                "template_link": obj.get("template_link"),
                "template_id": obj.get("template_id"),
                "apply_signing_order": obj.get("apply_signing_order"),
                "redirect_url": obj.get("redirect_url"),
                "decline_redirect_url": obj.get("decline_redirect_url"),
                "language": obj.get("language"),
                "expires_in": obj.get("expires_in"),
                "files": [FileInfo.from_dict(_item) for _item in obj["files"]]
                if obj.get("files") is not None
                else None,
                "fields": [
                    [DocumentResponseFieldsInnerInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["fields"]
                ]
                if obj.get("fields") is not None
                else None,
                "allow_decline": obj.get("allow_decline"),
                "allow_reassign": obj.get("allow_reassign"),
                "labels": [LabelInfo.from_dict(_item) for _item in obj["labels"]]
                if obj.get("labels") is not None
                else None,
                "checkbox_groups": [CheckboxGroupInfo.from_dict(_item) for _item in obj["checkbox_groups"]]
                if obj.get("checkbox_groups") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
