"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from signwell_sdk.models.attachment_request_info import AttachmentRequestInfo
from typing import Any, Optional, Set
from typing_extensions import Self


class DocumentFromTemplateResponseRecipientsInner(BaseModel):
    """
    DocumentFromTemplateResponseRecipientsInner
    """  # noqa: E501

    id: StrictStr | None = None
    name: StrictStr | None = None
    email: StrictStr
    role: StrictStr | None = None
    message: StrictStr | None = None
    subject: StrictStr | None = None
    send_email: StrictBool | None = None
    send_email_delay: StrictInt | None = None
    signing_order: StrictInt | None = None
    signing_url: StrictStr | None = None
    embedded_signing_url: StrictStr | None = None
    bounced: StrictBool | None = None
    bounced_details: StrictStr | None = None
    attachment_requests: List[AttachmentRequestInfo] | None = None
    passcode: StrictStr | None = None
    status: StrictStr | None = None
    placeholder_name: StrictStr | None = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "email",
        "role",
        "message",
        "subject",
        "send_email",
        "send_email_delay",
        "signing_order",
        "signing_url",
        "embedded_signing_url",
        "bounced",
        "bounced_details",
        "attachment_requests",
        "passcode",
        "status",
        "placeholder_name",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DocumentFromTemplateResponseRecipientsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachment_requests (list)
        _items_attachment_requests: list[Any] = []
        if self.attachment_requests:
            for _item_attachment_requests in self.attachment_requests:
                if _item_attachment_requests:
                    _items_attachment_requests.append(_item_attachment_requests.to_dict())
            _dict["attachment_requests"] = _items_attachment_requests
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict["message"] = None

        # set to None if subject (nullable) is None
        # and model_fields_set contains the field
        if self.subject is None and "subject" in self.model_fields_set:
            _dict["subject"] = None

        # set to None if send_email (nullable) is None
        # and model_fields_set contains the field
        if self.send_email is None and "send_email" in self.model_fields_set:
            _dict["send_email"] = None

        # set to None if send_email_delay (nullable) is None
        # and model_fields_set contains the field
        if self.send_email_delay is None and "send_email_delay" in self.model_fields_set:
            _dict["send_email_delay"] = None

        # set to None if signing_url (nullable) is None
        # and model_fields_set contains the field
        if self.signing_url is None and "signing_url" in self.model_fields_set:
            _dict["signing_url"] = None

        # set to None if embedded_signing_url (nullable) is None
        # and model_fields_set contains the field
        if self.embedded_signing_url is None and "embedded_signing_url" in self.model_fields_set:
            _dict["embedded_signing_url"] = None

        # set to None if bounced (nullable) is None
        # and model_fields_set contains the field
        if self.bounced is None and "bounced" in self.model_fields_set:
            _dict["bounced"] = None

        # set to None if bounced_details (nullable) is None
        # and model_fields_set contains the field
        if self.bounced_details is None and "bounced_details" in self.model_fields_set:
            _dict["bounced_details"] = None

        # set to None if passcode (nullable) is None
        # and model_fields_set contains the field
        if self.passcode is None and "passcode" in self.model_fields_set:
            _dict["passcode"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of DocumentFromTemplateResponseRecipientsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "email": obj.get("email"),
                "role": obj.get("role"),
                "message": obj.get("message"),
                "subject": obj.get("subject"),
                "send_email": obj.get("send_email"),
                "send_email_delay": obj.get("send_email_delay"),
                "signing_order": obj.get("signing_order"),
                "signing_url": obj.get("signing_url"),
                "embedded_signing_url": obj.get("embedded_signing_url"),
                "bounced": obj.get("bounced"),
                "bounced_details": obj.get("bounced_details"),
                "attachment_requests": [AttachmentRequestInfo.from_dict(_item) for _item in obj["attachment_requests"]]
                if obj.get("attachment_requests") is not None
                else None,
                "passcode": obj.get("passcode"),
                "status": obj.get("status"),
                "placeholder_name": obj.get("placeholder_name"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
