"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FieldType(str, Enum):
    """
    Type of signing field
    """

    """
    allowed enum values
    """
    INITIALS = "initials"
    SIGNATURE = "signature"
    CHECKBOX = "checkbox"
    DATE = "date"
    SELECT = "select"
    TEXT = "text"
    DROPDOWN = "dropdown"
    AUTOFILL_COMPANY = "autofill_company"
    AUTOFILL_EMAIL = "autofill_email"
    AUTOFILL_FIRST_NAME = "autofill_first_name"
    AUTOFILL_LAST_NAME = "autofill_last_name"
    AUTOFILL_NAME = "autofill_name"
    AUTOFILL_PHONE = "autofill_phone"
    AUTOFILL_TITLE = "autofill_title"
    AUTOFILL_DATE_SIGNED = "autofill_date_signed"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FieldType from a JSON string"""
        return cls(json.loads(json_str))
