"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from signwell_sdk.models.additional_fields_inner_inner_value import AdditionalFieldsInnerInnerValue
from signwell_sdk.models.date_format import DateFormat
from signwell_sdk.models.dropdown_option import DropdownOption
from signwell_sdk.models.field_type import FieldType
from signwell_sdk.models.text_validation import TextValidation
from typing import Any, Optional, Set
from typing_extensions import Self


class FieldsInnerInner(BaseModel):
    """
    FieldsInnerInner
    """  # noqa: E501

    x: Union[StrictFloat, StrictInt] = Field(
        description="Horizontal value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located."
    )
    y: Union[StrictFloat, StrictInt] = Field(
        description="Vertical value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located."
    )
    page: StrictInt = Field(
        description="The page number within the file. If the page does not exist within the file then the field won't be created."
    )
    recipient_id: StrictStr = Field(
        description="Unique identifier of the recipient assigned to the field. Recipients assigned to fields will be the only ones that will see and be able to complete those fields."
    )
    type: FieldType
    required: StrictBool | None = Field(
        default=True,
        description="Whether the field must be completed by the recipient. Defaults to `true` except for checkbox type fields.",
    )
    label: StrictStr | None = Field(
        default=None, description="Text and Date fields only: label that is displayed when the field is empty."
    )
    value: AdditionalFieldsInnerInnerValue | None = None
    api_id: StrictStr | None = Field(
        default=None,
        description="Unique identifier of the field. Useful when needing to reference specific field values or update a document and its fields.",
    )
    name: StrictStr | None = Field(
        default=None,
        description="Checkbox fields only. At least 2 checkbox fields in an array of fields must be assigned to the same recipient and grouped with selection requirements.",
    )
    validation: TextValidation | None = None
    fixed_width: StrictBool | None = Field(
        default=False,
        description="Text fields only: whether the field width will stay fixed and text will display in multiple lines, rather than one long line. If set to `false` the field width will automatically grow horizontally to fit text on one line. Defaults to `false`.",
    )
    lock_sign_date: StrictBool | None = Field(
        default=False,
        description="Date fields only: makes fields readonly and automatically populates with the date the recipient signed. Defaults to `false`.",
    )
    date_format: DateFormat | None = None
    height: Union[StrictFloat, StrictInt] | None = Field(
        default=None,
        description="Height of the field (in pixels). Maximum height varies by field type: Signature/Initials (200px), others (74px). When using text tags if the height is greater than the maximum height, the height will be set to the maximum height.",
    )
    width: Union[StrictFloat, StrictInt] | None = Field(
        default=None,
        description="Width of the field (in pixels). For text fields, width will auto-grow unless `fixed_width` is true.",
    )
    options: List[DropdownOption] | None = Field(
        default=None, description="Array of dropdown options (for dropdown/select fields only)"
    )
    default_option: StrictStr | None = Field(
        default=None, description="Default selected option (for dropdown/select fields only)"
    )
    allow_other: StrictBool | None = Field(
        default=False, description='Whether to allow "Other" option with text input (for dropdown/select fields only)'
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "x",
        "y",
        "page",
        "recipient_id",
        "type",
        "required",
        "label",
        "value",
        "api_id",
        "name",
        "validation",
        "fixed_width",
        "lock_sign_date",
        "date_format",
        "height",
        "width",
        "options",
        "default_option",
        "allow_other",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of FieldsInnerInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict["value"] = self.value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items_options: list[Any] = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items_options.append(_item_options.to_dict())
            _dict["options"] = _items_options
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of FieldsInnerInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "x": obj.get("x"),
                "y": obj.get("y"),
                "page": obj.get("page"),
                "recipient_id": obj.get("recipient_id"),
                "type": obj.get("type"),
                "required": obj.get("required") if obj.get("required") is not None else True,
                "label": obj.get("label"),
                "value": AdditionalFieldsInnerInnerValue.from_dict(obj["value"])
                if obj.get("value") is not None
                else None,
                "api_id": obj.get("api_id"),
                "name": obj.get("name"),
                "validation": obj.get("validation"),
                "fixed_width": obj.get("fixed_width") if obj.get("fixed_width") is not None else False,
                "lock_sign_date": obj.get("lock_sign_date") if obj.get("lock_sign_date") is not None else False,
                "date_format": obj.get("date_format"),
                "height": obj.get("height"),
                "width": obj.get("width"),
                "options": [DropdownOption.from_dict(_item) for _item in obj["options"]]
                if obj.get("options") is not None
                else None,
                "default_option": obj.get("default_option"),
                "allow_other": obj.get("allow_other") if obj.get("allow_other") is not None else False,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
