"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Any, Optional, Set
from typing_extensions import Self


class Nom151CertificateResponseNom151(BaseModel):
    """
    Nom151CertificateResponseNom151
    """  # noqa: E501

    status: StrictStr = Field(description="Certificate status (pending, issued, failed)")
    transaction_id: StrictStr = Field(description="RSA signature / Transaction ID", alias="transactionId")
    hash: StrictStr = Field(description="Document digest (SHA-256 hash)")
    folio: StrictStr = Field(description="Certificate number / Folio")
    issued_at: datetime = Field(description="Certificate issuance timestamp", alias="issuedAt")
    provider: StrictStr = Field(description="Certificate provider (e.g., SeguriData)")
    validation_url: StrictStr = Field(description="URL to validate the certificate", alias="validationUrl")
    constancia: StrictStr = Field(description="Base64-encoded certificate file")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "status",
        "transactionId",
        "hash",
        "folio",
        "issuedAt",
        "provider",
        "validationUrl",
        "constancia",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Nom151CertificateResponseNom151 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of Nom151CertificateResponseNom151 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "transactionId": obj.get("transactionId"),
                "hash": obj.get("hash"),
                "folio": obj.get("folio"),
                "issuedAt": obj.get("issuedAt"),
                "provider": obj.get("provider"),
                "validationUrl": obj.get("validationUrl"),
                "constancia": obj.get("constancia"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
