"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Any, Optional, Set
from typing_extensions import Self


class TemplateRecipientsInner(BaseModel):
    """
    TemplateRecipientsInner
    """  # noqa: E501

    id: StrictStr = Field(
        description="A unique identifier that you will give to each recipient. We recommend numbering sequentially from 1 to X. IDs are required for associating recipients to fields and more."
    )
    name: StrictStr | None = Field(default=None, description="Name of the recipient.")
    email: StrictStr = Field(description="Email address for the recipient.")
    placeholder_name: StrictStr | None = Field(
        default=None, description="The name of the placeholder you want this recipient assigned to."
    )
    passcode: StrictStr | None = Field(
        default=None,
        description="If set, signers assigned with a passcode will be required to enter the passcode before they’re able to view and complete the document.",
    )
    subject: StrictStr | None = Field(
        default=None,
        description="Email subject for the signature request that the recipient will see. Overrides the general subject for the template.",
    )
    message: StrictStr | None = Field(
        default=None,
        description="Email message for the signature request that the recipient will see. Overrides the general message for the template.",
    )
    send_email: StrictBool | None = Field(
        default=False,
        description="Applies on when `embedded_signing` is `true`. By default, recipients are not notified through email to sign when doing embedded signing. Setting this to `true`  will send a notification email to the recipient. Default is `false`.",
    )
    send_email_delay: StrictInt | None = Field(
        default=0,
        description="If `send_email` is `true` recipients will receive a new document notification immediately. In the case of embedded signing, you can delay this notification to only send if the document is not completed within a few minutes. The email notification will not go out if the document is completed before the delay time is over. Valid values are in minutes ranging from `0` to `60`. Defaults to `0`.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "email",
        "placeholder_name",
        "passcode",
        "subject",
        "message",
        "send_email",
        "send_email_delay",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TemplateRecipientsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of TemplateRecipientsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "email": obj.get("email"),
                "placeholder_name": obj.get("placeholder_name"),
                "passcode": obj.get("passcode"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "send_email": obj.get("send_email") if obj.get("send_email") is not None else False,
                "send_email_delay": obj.get("send_email_delay") if obj.get("send_email_delay") is not None else 0,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
