"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TextValidation(str, Enum):
    """
    Validation rule for text fields
    """

    """
    allowed enum values
    """
    NO_TEXT_VALIDATION = "no_text_validation"
    NUMBERS = "numbers"
    LETTERS = "letters"
    EMAIL_ADDRESS = "email_address"
    US_PHONE_NUMBER = "us_phone_number"
    US_ZIP_CODE = "us_zip_code"
    US_SSN = "us_ssn"
    US_AGE = "us_age"
    ALPHANUMERIC = "alphanumeric"
    US_BANK_ROUTING_NUMBER = "us_bank_routing_number"
    US_BANK_ACCOUNT_NUMBER = "us_bank_account_number"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TextValidation from a JSON string"""
        return cls(json.loads(json_str))
