"""
SignWell Developer API

API for creating, managing, and tracking electronic signature workflows.

The version of the OpenAPI document: v1
Contact: support@signwell.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from signwell_sdk.models.checkbox_groups_inner import CheckboxGroupsInner
from signwell_sdk.models.label_request import LabelRequest
from typing import Any, Optional, Set
from typing_extensions import Self


class UpdateDocumentAndSendRequest(BaseModel):
    """
    UpdateDocumentAndSendRequest
    """  # noqa: E501

    test_mode: StrictBool | None = Field(
        default=False,
        description="Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`",
    )
    name: StrictStr | None = Field(default=None, description="The name of the document.")
    subject: StrictStr | None = Field(
        default=None,
        description="Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).",
    )
    message: StrictStr | None = Field(
        default=None,
        description="Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).",
    )
    expires_in: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=None,
        description="Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).",
    )
    reminders: StrictBool | None = Field(
        default=True,
        description="Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.",
    )
    apply_signing_order: StrictBool | None = Field(
        default=False,
        description="When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.",
    )
    api_application_id: StrictStr | None = Field(
        default=None,
        description="Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings",
    )
    embedded_signing: StrictBool | None = Field(
        default=False,
        description="When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.",
    )
    embedded_signing_notifications: StrictBool | None = Field(
        default=False,
        description="On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`",
    )
    custom_requester_name: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.",
    )
    custom_requester_email: StrictStr | None = Field(
        default=None,
        description="Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.",
    )
    redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to after successfully signing a document."
    )
    allow_decline: StrictBool | None = Field(
        default=True,
        description="Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.",
    )
    allow_reassign: StrictBool | None = Field(
        default=True,
        description="In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.",
    )
    decline_redirect_url: StrictStr | None = Field(
        default=None, description="A URL that recipients are redirected to if the document is declined."
    )
    metadata: Dict[str, StrictStr] | None = Field(
        default=None,
        description="Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.",
    )
    labels: List[LabelRequest] | None = Field(
        default=None,
        description="Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels. Updating labels on a document will replace any existing labels for that document.",
    )
    checkbox_groups: List[CheckboxGroupsInner] | None = Field(
        default=None,
        description="Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.",
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "test_mode",
        "name",
        "subject",
        "message",
        "expires_in",
        "reminders",
        "apply_signing_order",
        "api_application_id",
        "embedded_signing",
        "embedded_signing_notifications",
        "custom_requester_name",
        "custom_requester_email",
        "redirect_url",
        "allow_decline",
        "allow_reassign",
        "decline_redirect_url",
        "metadata",
        "labels",
        "checkbox_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of UpdateDocumentAndSendRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items_labels: list[Any] = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items_labels.append(_item_labels.to_dict())
            _dict["labels"] = _items_labels
        # override the default output from pydantic by calling `to_dict()` of each item in checkbox_groups (list)
        _items_checkbox_groups: list[Any] = []
        if self.checkbox_groups:
            for _item_checkbox_groups in self.checkbox_groups:
                if _item_checkbox_groups:
                    _items_checkbox_groups.append(_item_checkbox_groups.to_dict())
            _dict["checkbox_groups"] = _items_checkbox_groups
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of UpdateDocumentAndSendRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "test_mode": obj.get("test_mode") if obj.get("test_mode") is not None else False,
                "name": obj.get("name"),
                "subject": obj.get("subject"),
                "message": obj.get("message"),
                "expires_in": obj.get("expires_in"),
                "reminders": obj.get("reminders") if obj.get("reminders") is not None else True,
                "apply_signing_order": obj.get("apply_signing_order")
                if obj.get("apply_signing_order") is not None
                else False,
                "api_application_id": obj.get("api_application_id"),
                "embedded_signing": obj.get("embedded_signing") if obj.get("embedded_signing") is not None else False,
                "embedded_signing_notifications": obj.get("embedded_signing_notifications")
                if obj.get("embedded_signing_notifications") is not None
                else False,
                "custom_requester_name": obj.get("custom_requester_name"),
                "custom_requester_email": obj.get("custom_requester_email"),
                "redirect_url": obj.get("redirect_url"),
                "allow_decline": obj.get("allow_decline") if obj.get("allow_decline") is not None else True,
                "allow_reassign": obj.get("allow_reassign") if obj.get("allow_reassign") is not None else True,
                "decline_redirect_url": obj.get("decline_redirect_url"),
                "metadata": obj.get("metadata"),
                "labels": [LabelRequest.from_dict(_item) for _item in obj["labels"]]
                if obj.get("labels") is not None
                else None,
                "checkbox_groups": [CheckboxGroupsInner.from_dict(_item) for _item in obj["checkbox_groups"]]
                if obj.get("checkbox_groups") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
